numaproj/numaplane

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

Add issue template

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

Add PR template and codeowners.

PR template and CodeOwners

---

.github/workflows/ci.yaml
.gitignore
Makefile

- Verified all make taregts
- Added the Lint and unit test in github action

Fix all make targets and add lint, unit tests in github action

---

config/install.yaml
config/manager/numaflow-controller-definitions-config.yaml
internal/controller/pipelinerollout_controller.go
internal/kubernetes/dynamic_client.go
tests/manifests/controller_definitions.yaml

Fixes #14 
This introduced the pipeline pausing logic when pipeline spec is updated. However, currently this PR always disable pause as https://github.com/numaproj/numaplane/issues/4 is not there yet.
Local cluster testing

feat: support pipeline pause with pipeline spec change

---

config/install.yaml
config/manager/numaflow-controller-definitions-config.yaml
tests/manifests/controller_definitions.yaml

Update Numaflow controller image version for `1.2.1`.

Update controller image version for `1.2.1`

---

internal/controller/numaflowcontrollerrollout_controller.go
internal/sync/cache.go
internal/sync/cache_test.go
internal/sync/testdata/pipeline-live.yaml
internal/util/kubernetes/kubernetes.go
internal/util/kubernetes/kubernetes_test.go
pkg/apis/numaplane/v1alpha1/groupversion_info.go

Clean up unrelated/unused code mostly related to GitSync.
Unit test

chore: clean up unused code

---

internal/controller/isbservicerollout_controller_test.go

Fixes #57 
Update ISBServiceRollout controller unit tests to use similar tests done on PipelineRollout controller
ran make test locally to verify test pass

Update ISBServiceRollout controller unit tests

---

internal/controller/isbservicerollout_controller.go
internal/controller/isbservicerollout_controller_test.go
internal/controller/pipelinerollout_controller.go
internal/controller/pipelinerollout_controller_test.go
internal/util/kubernetes/kubernetes.go

Fixes #64 
Issue #64 details the modifications.
Added new unit tests to cover the case in which a child resource changes compared to the owner resource.

Auto healing

---

internal/controller/pipelinerollout_controller.go

`processPipelineStatus()` was previously being called from the function `applyCRSpec()`, but really incorporating the child's status into ours is something we want to do independent of applying a spec.
1. applied PipelineRollout with no ISBServiceRollout available
2. observed that Pipeline was unhealthy due to no ISBService, and therefore PipelineRollout was set to ChildResourcesHealthy=false
3. applied ISBServiceRollout
4. observed that Pipeline became healthy, and then PipelineRollout got set to ChildResourcesHealthy=true

fix: relocate call to processPipelineStatus()

---

internal/controller/numaflowcontrollerrollout_controller_test.go
internal/controller/suite_test.go
tests/config/controller-definitions-config.yaml

Fixes #22 
- Verified the Numaplane controller create feature and update feature
- Add unit test for Numaplane controller Create and update
- Validated it in local kubernetes cluster

Add unit test for controller rollout create and update

---

config/crd/bases/numaplane.numaproj.io_isbservicerollouts.yaml
config/crd/bases/numaplane.numaproj.io_numaflowcontrollerrollouts.yaml
config/crd/bases/numaplane.numaproj.io_pipelinerollouts.yaml
config/install.yaml
internal/controller/isbservicerollout_controller.go
internal/controller/isbservicerollout_controller_test.go
internal/controller/numaflowcontrollerrollout_controller.go
internal/controller/numaflowcontrollerrollout_controller_test.go
internal/controller/pipelinerollout_controller.go
internal/controller/pipelinerollout_controller_test.go
internal/util/kubernetes/kubernetes.go
pkg/apis/numaplane/v1alpha1/pipelinerollout_types.go
pkg/apis/numaplane/v1alpha1/status_types.go

Fixes #88 #85 
Added ObservedGeneration to the rollouts Status and setting Phase and ConditionConfigured based on child resource status.
NOTE: Numaflow needs to be updated to include ObservedGeneration status.
Unable to test until Numaflow is updated to include ObservedGeneration status. Unit tests will fail until then.

Observed Generation

---

.github/workflows/ci.yaml

Fixes #80 
Enable CodeCov in CI.

chore: Enable codecov

---

cmd/main.go
go.mod
internal/controller/isbservicerollout_controller.go
internal/controller/isbservicerollout_controller_test.go
internal/controller/numaflowcontrollerrollout_controller.go
internal/controller/pipelinerollout_controller.go
internal/controller/pipelinerollout_controller_test.go
internal/controller/suite_test.go
internal/util/metrics/metrics.go

Fixes https://github.com/numaproj/numaplane/issues/11
Add metrics data for pipeline, isb and numaflow counter
```bash
example-namespace    isbsvc-my-isbsvc-js-0                           3/3     Running     0          5m3s
example-namespace    isbsvc-my-isbsvc-js-1                           3/3     Running     0          5m3s
example-namespace    isbsvc-my-isbsvc-js-2                           3/3     Running     0          5m3s
example-namespace    my-pipeline-cat-0-nseys                         2/2     Running     0          4m43s
example-namespace    my-pipeline-daemon-8447bdf554-8gzdl             0/1     Init:0/1    0          4m42s
example-namespace    my-pipeline-in-0-kmw5s                          0/1     Init:0/1    0          4m43s
example-namespace    my-pipeline-out-0-8z2tx …
```

feat: Add metrics for pipeline, isb and numaflow counter

---

internal/controller/pipelinerollout_controller.go
internal/controller/pipelinerollout_controller_test.go

Yes
Fixes  https://github.com/numaproj/numaplane/issues/98
Modified PipelineRolloutReconciler reconcile method to Add ISBSVC name as a label to the Pipeline
Yet to test

Added Isbsvc service name to the pipeline label

---

config/kustomize/examples/transformer/kustomization.yaml
config/kustomize/examples/transformer/my-isbservicerollout.yaml
config/kustomize/examples/transformer/my-pipelinerollout.yaml
config/kustomize/numaplane-transformer-config.yaml

Modify the Kustomize Transformer config file based on the latest rollout spec changes.
Manually tested by using the kustomize binary and `kubectl apply -k` command on the `config/kustomize/examples/transformer` directory

Update Kustomize Transformer Config

---

tests/manifests/controller_definitions.yaml

Adds `v1.1.7` fullSpec to the NumaflowController version definitions ConfigMap.

test: add NumaflowController version v1.1.7 to test ConfigMap

---

tests/e2e/functional_test.go
tests/manifests/controller_definitions.yaml

Update controller-definitions.yaml to use a newer release candidate. This rc includes changes that will be needed for test cases. 
Ran `make test` and `make test-e2e` with recreated configmap.

test: update controller definitions for testing

---

internal/controller/pipelinerollout_controller.go
internal/controller/pipelinerollout_controller_test.go

Fixes #45 
Adds a check in PipelineRollout reconciliation to check that the existing Pipeline with the PipelineRollout's name we get in the current namespace is owned by our PipelineRollout. If this Pipeline was created manually by a user or another PipelineRollout, the PipelineRollout should fail automatically.
We verify the ownership of the Pipeline by checking the `ownerReferences` specifically that it is not empty and contains an ownerReference to `kind: PipelineRollout` with the UID of the PipelineRollout.
Added a unit test case and ran it using `make test`
Created a Pipeline then PipelineRollout locally to see that it showed as Failed upon creation

feat: PipelineRollout installation will fail if Pipeline already exists

---

config/install.yaml
config/manager/controller-config.yaml

We should not need to cache secrets.
make manifests

chore: remove secrets from watched resources

---

internal/controller/pipelinerollout_controller.go

Fixes #189 
Separate out the logic for deriving the "ChildResourcesHealthy" Condition value from the "PipelinePaused" Condition. This way we better ensure that the value for each of them is set one way or another.
Tested with both `dataLossPrevention` true and false. Modified PipelineRollout a few times and each time did `kubectl get pipeline -o yaml` to check the Conditions' Status was correct as far as message, reason, and observedGeneration.

fix: separate out logic for each Condition

---

.github/workflows/pr.yaml

If all PRs need to start with "feat", "fix", etc, then it should be easier to create the Release notes (potentially automated) as well as create patch releases. This CI job adds that.
Using [this](https://github.com/amannn/action-semantic-pull-request). I grabbed this Github Workflow from argo-workflows repo. You can see a random [PR](https://github.com/argoproj/argo-workflows/pull/13463) that performs that check.

feat: Check PR Title's semantic conformance

---

internal/controller/isbservicerollout_controller.go
internal/controller/pipelinerollout_controller.go

Fixes #211 
Check if the spec needs to be updated for updates without data loss prevention.

fix: check if spec needs to be updated.

---

config/install.yaml

- Fix the codegen failure
Failure detail: https://github.com/numaproj/numaplane/actions/runs/10685701760/job/29619164588

fix: Update install.yaml to fix codegen failure

---

config/kustomize/examples/transformer/kustomization.yaml
config/kustomize/examples/transformer/my-monovertexrollout.yaml
config/kustomize/numaplane-transformer-config.yaml

Modify the Kustomize Transformer config file based on the latest rollout spec changes with monovertex
Manually tested by using the kustomize binary and `kubectl apply -k `command on the config/kustomize/examples/transformer directory

chore: Update Kustomize Transformer Config with monovertex

---

Dockerfile
go.mod
go.sum

Fixes #TODO
- Update kubernetes version and remove unused binary to fix security issue
- Verified in local kind cluster after deploying PipelineRollout and MonovertexRollout

fix: Update version and remove unused package to fix security issue

---

internal/controller/pipelinerollout_controller.go
internal/controller/pipelinerollout_ppnd.go

This PRs remove a redundant check for in progress upgrade strategy
`make test`

chore: remove redundant check for in progress upgrade strategy

---

Makefile
internal/controller/isbservicerollout_controller.go
internal/controller/monovertexrollout_controller.go
internal/controller/numaflowcontrollerrollout_controller.go
internal/controller/pause_requester.go
internal/controller/pipelinerollout_controller.go
internal/controller/pipelinerollout_progressive.go
internal/util/kubernetes/unstructured_util.go
internal/util/kubernetes/unstructured_util_test.go
internal/util/metrics/metrics.go

feat: Use informer cache for monovertex, pipeline and ISB Services

---

internal/controller/isbservicerollout_controller.go

Fixes #TODO
If strategy is Progressive, we will do direct apply for isbService instead for now.
This is a temp change that will be changed back later.

fix: tmp change to use directapply instead of prog for isbsvc

---

internal/controller/isbservicerollout_controller.go
internal/controller/numaflowcontrollerrollout_controller.go
internal/controller/ppnd_pause_requester.go
internal/usde/usde.go
internal/util/kubernetes/unstructured_util.go
internal/util/kubernetes/unstructured_util_test.go

Fixes
ISBService Controller:  https://github.com/numaproj/numaplane/issues/143
Removed the usages of Generic Object struct and use Unstructured.

fix: Refactor isbservice_controller to eliminate use of GenericObject

---

tests/manifests/default/controller_def_1.4.0.yaml

fix numaflow controller definition 1.4.0

fix: numaflow controller definition 1.4.0

---

config/install.yaml
config/manager/usde-config.yaml
internal/controller/config/usde_config.go
internal/controller/isbservicerollout/isbservicerollout_controller_test.go
internal/controller/pipelinerollout/pipelinerollout_controller_test.go
internal/usde/usde.go
internal/usde/usde_test.go
internal/util/kubernetes/config_watcher.go
internal/util/kubernetes/config_watcher_test.go
internal/util/util.go
tests/e2e/functional_test.go
tests/manifests/special-cases/ppnd/usde-config.yaml
tests/manifests/special-cases/progressive/usde-config.yaml

Fixes #330 #407 
Changed USDE logic from using a list of direct-apply fields to a list of data-loss fields.
Updated unit tests, executed e2e tests, manual tests.

feat: USDE with data loss fields config

---

config/install.yaml
config/manager/usde-config.yaml
tests/e2e/functional_test.go
tests/manifests/special-cases/ppnd/usde-config.yaml
tests/manifests/special-cases/progressive/usde-config.yaml

Updating the e2e test to prove that [this](https://github.com/numaproj/numaplane/issues/330) issue was fixed.
Also, adding comments to explain the fields in the usde_config.yaml

chore: update e2e to prove usde changes fixed issue, and add comments to USDE config

---

config/install.yaml
config/manager/controller-config.yaml
config/manager/usde-config.yaml
internal/controller/config/config.go
internal/controller/config/config_test.go
internal/controller/config/usde_config.go
internal/controller/config/user_config.go
internal/controller/ginkgo_suite_test.go
internal/controller/isbservicerollout/isbservicerollout_controller_test.go
internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller_test.go
internal/controller/pipelinerollout/pipelinerollout_controller_test.go
internal/usde/usde.go
internal/usde/usde_test.go
internal/util/kubernetes/config_watcher.go
tests/config/testconfig.yaml
tests/config/testconfig2.yaml
tests/manifests/default/config.yaml
tests/manifests/special-cases/ppnd/usde-config.yaml
tests/manifests/special-cases/progressive/usde-config.yaml

Fixes #415 
Moved the `defaultUpgradeStrategy` env var from USDE Config to `numaplane-controller-config`.
Unit tests and e2e tests.

chore: move defaultUpgradeStrategy from USDE config to numaplane-controller-config

---

internal/controller/common/numaflowtypes/monovertex.go
internal/controller/common/numaflowtypes/pipeline.go
internal/controller/isbservicerollout/isbservicerollout_controller.go
internal/controller/isbservicerollout/isbservicerollout_controller_test.go
internal/controller/monovertexrollout/monovertexrollout_controller.go
internal/controller/monovertexrollout/monovertexrollout_controller_test.go
internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller.go
internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller_test.go
internal/controller/pipelinerollout/pipelinerollout_controller.go
internal/controller/pipelinerollout/pipelinerollout_controller_test.go
internal/controller/pipelinerollout/pipelinerollout_ppnd.go
internal/controller/ppnd/ppnd_pause.go
internal/controller/ppnd/ppnd_pause_requester.go
internal/controller/progressive/progressive.go
internal/usde/usde.go
internal/usde/usde_test.go
internal/util/kubernetes/unstructured_util.go
internal/util/kubernetes/unstructured_util_test.go

Fixes https://github.com/numaproj/numaplane/issues/143
- Remove the dependenency from GenericObject and it's conversion for monovertex, pipeline and numaflow controller
Verified on local k8s cluster

fix: Refactor monovertex and pipeline controller

---

.github/pull_request_template.md

Catch potential backward incompatibilities beforehand.

chore: add backward incompatibility question to PR template

---

go.mod
internal/controller/config/config_test.go
internal/controller/isbservicerollout/isbservicerollout_controller.go
internal/controller/monovertexrollout/monovertexrollout_controller.go
internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller.go
internal/controller/pipelinerollout/pipelinerollout_controller.go
internal/controller/pipelinerollout/pipelinerollout_controller_test.go
internal/usde/usde.go
internal/util/kubernetes/unstructured_util.go
internal/util/maps.go
internal/util/util.go
internal/util/util_test.go

Fixes https://github.com/numaproj/numaplane/issues/456

fix: Add compare struct method to compare it without num type

---

internal/controller/isbservicerollout/isbservicerollout_controller.go
internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller.go

Replaced USDE NoOp strategy for Apply in NumaflowController and ISBSvc rollouts.
Unit tests and E2E tests.
None

chore: replace USDE NoOp strategy for Apply in NumaflowController and ISBSvc rollouts

---

config/install.yaml
config/manager/usde-config.yaml
internal/controller/config/usde_config.go
internal/controller/isbservicerollout/isbservicerollout_controller.go
internal/controller/isbservicerollout/isbservicerollout_controller_test.go
internal/controller/monovertexrollout/monovertexrollout_controller.go
internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller.go
internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller_test.go
internal/controller/pipelinerollout/pipelinerollout_controller.go
internal/controller/pipelinerollout/pipelinerollout_controller_test.go
internal/usde/usde.go
internal/usde/usde_test.go
internal/util/kubernetes/config_watcher.go
internal/util/kubernetes/config_watcher_test.go

Fixes #402 
Modified the USDE logic to include USDE Config changes with the new `progressive` and `recreate` lists.
Unit tests and e2e tests.
This PR should not cause backward incompatibility issues unless the USDE ConfigMap cannot be updated during upgrade.

feat: modified USDE logic to include USDE Config changes with the new progressive and recreate lists

---

internal/controller/monovertexrollout/monovertexrollout_progressive.go
internal/controller/pipelinerollout/pipelinerollout_progressive.go

Fixes #514 
Updated the child health assessment function for Pipeline and Monovertex.
Unit and E2E tests.
None

fix: pipeline and monovertex assessment fix for unknown.

---

internal/controller/common/test_common.go
internal/controller/isbservicerollout/isbservicerollout_controller_test.go
internal/controller/pipelinerollout/pipelinerollout_controller_test.go

Fixes #493 
Introduced a unit test for performing progressive update for ISBServiceRollout
just the unit test itself
N/A

chore: unit test for isbsvc blue/green

---

pkg/apis/numaplane/v1alpha1/status_types.go

fix: IsAssessUntilSet func was performing wrong time comparison.

---

internal/util/kubernetes/config_watcher.go

Fixes https://github.com/numaproj/numaplane/issues/542

feat: Add support for modify controller def configmap

---

internal/controller/isbservicerollout/isbservicerollout_controller.go
internal/controller/monovertexrollout/monovertexrollout_controller.go
internal/controller/numaflowcontroller/numaflowcontroller_controller.go
internal/controller/pipelinerollout/pipelinerollout_controller.go

If we are going to create an event for an error, we should log it in the numaplane logs as well.
(BTW, I had trouble finding the event in splunk.)
This is just a new log message.
n/a

chore: log errors in numaplane that we issue events for

---

hack/numaflow-controller-def-generator/numaflow-controller-def-generator.sh

I have `yq` installed through homebrew, which is different from the one which this script installs (`github.com/mikefarah/yq/v4@latest`). Therefore, clarifying the one to use is that one.
Ran `./hack/numaflow-controller-def-generator/numaflow-controller-def-generator.sh 1.3.3` and verified file was generated.
N/A

chore: clarify which yq is used in numaflow controller generation script

---

config/install.yaml
config/manager/controller-config.yaml
config/samples/numaplane.numaproj.io_v1alpha1_isbservicerollout.yaml
config/samples/numaplane.numaproj.io_v1alpha1_monovertexrollout.yaml
config/samples/numaplane.numaproj.io_v1alpha1_pipelinerollout.yaml
internal/controller/common/riders/rider.go
internal/controller/isbservicerollout/isbservicerollout_controller.go
internal/controller/monovertexrollout/monovertexrollout_controller.go
internal/controller/pipelinerollout/pipelinerollout_controller.go
internal/usde/usde.go
internal/util/kubernetes/unstructured_util.go

Minor modifications to the `rollout-riders` branch to clean things up before merging. 
tried deploying each of the sample Rollouts to make sure they could still be deployed (along with specified Riders)
N/A

chore: Prepare to merge rollout-riders

---

internal/controller/progressive/progressive.go

Fixes #708 
The issue is that if you try to progressively upgrade a paused Pipeline/MonoVertex, it never passes or fails the call to `AssessUpgradingChild()` because that was only looking for "Running" and "Failed" phases.
Modified to this:
Not only is "Running" considered a healthy phase, but assuming that `desiredPhase=Paused`, "Pausing" and "Paused" are both considered healthy as well.
Tried creating a PipelineRollout with desiredPhase=Paused, and then updated it in a way to trigger a progressive upgrade. Observed that new pipeline was deemed "Successful" and replaced the old one. 
Repeated experiment with MonoVertexRollout
N/A

fix: make progressive work for paused pipelines/monovertices

---

internal/controller/progressive/progressive.go

While I started working on the issue to do "premature cancellation of in progress rollout" for progressive, I realized there was a small refactor that could be done.
At some point, I was trying to save on Kubernetes API live calls by only getting the live version in certain circumstances if I really needed it. 
But now with the current code, it seems like the savings is very limited and is just making the code harder to read.

chore: remove redundant calls

---

internal/controller/isbservicerollout/isbservicerollout_controller.go
internal/controller/monovertexrollout/monovertexrollout_controller.go
internal/controller/numaflowcontroller/numaflowcontroller_controller.go
internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller.go
internal/controller/pipelinerollout/pipelinerollout_controller.go

Add debug logger for rollout health metrics

fix: Add debug logger for metrics data

---

Makefile
tests/manifests/default/controller_def_1.6.0.yaml

Fixes #840 
This seems like maybe it was a temporary hiccup from github.

chore: try restoring bash script

---

config/samples/numaplane.numaproj.io_v1alpha1_pipelinerollout.yaml
internal/controller/pipelinerollout/pipelinerollout_controller_test.go
internal/sync/testdata/pipeline-config.yaml
internal/sync/testdata/pipeline-live.yaml
internal/usde/usde_test.go
tests/e2e/concurrent-e2e/concurrent_test.go
tests/e2e/functional-pipeline-e2e/pipeline_test.go
tests/e2e/pipeline.go
tests/e2e/ppnd-e2e/ppnd_test.go
tests/e2e/progressive-analysis-pipeline-e2e/analysis_pipeline_test.go
tests/e2e/progressive-pipeline-e2e/pipeline_test.go
tests/e2e/rider-e2e/rider_test.go
tests/e2e/rollback-e2e/rollback_test.go

Part of: https://github.com/numaproj/numaplane/issues/811

fix: Replace builtin with container

---

tests/e2e/progressive-pipeline-e2e/pipeline_test.go

partial fix to #873 
The Progressive Pipeline test updates isbsvc and pipeline at the same time. We need to make the test less rigid as far as what order updates occur in. 
This is a partial fix to the issue for this test overall, since I noticed a failure for this particular test case.
ran CI a few times

fix: make test less rigid as far as order of operations

---

config/samples/numaplane.numaproj.io_v1alpha1_monovertexrollout.yaml
config/samples/numaplane.numaproj.io_v1alpha1_pipelinerollout.yaml

chore: remove the update to sample monovertexrollout and pipelinerollout adding HPA rider
