numaproj/numaplane

internal/sync/cache.go, internal/sync/cache_test.go
correct the comment for `LiveStateCache.GetManagedLiveObjs` and fix the unit test failure
=> chore: correct the comment for GetManagedLiveObjs

internal/controller/numaflowcontrollerrollout_controller_test.go
Yes
Fixes (https://github.com/numaproj/numaplane/issues/21)
Added ginkgo testsuite [test](https://github.com/numaproj/numaplane/blob/ownerRefunitTest/internal/controller/numaflowcontrollerrollout_controller_test.go#L87) for `applyOwnershipToManifests` function in the code .
As its a unit test ,it has been tested by running `make test` command
=> Added test case for applying ownership reference To Controller Rollout

internal/controller/isbservicerollout_controller.go, internal/controller/pipelinerollout_controller.go
Fixes #5 
Using events handler `EnqueueRequestForOwner` with the controller watch when watching for events on the child resources (Pipeline and ISBService). This reduces the number of Reconcile calls to only handle changes related to the owned resource.
Manually tested changes and observed that the number of Reconcile calls is reduced for the same operations.
=> fix: watch with EnqueueRequestForOwner to avoid multiple reconcile calls

internal/controller/isbservicerollout_controller.go, internal/controller/pipelinerollout_controller.go, internal/controller/pipelinerollout_controller_test.go
Fixes #61 
Implemented `RetryOnConflict` to get the latest version of the resource and update it's status with the status of the in-memory object modified during reconciliation.
Running unit tests multiple times will no longer show the error mentioned in the issue.
=> fix: avoid error on status update

internal/controller/numaflowcontrollerrollout_controller_test.go
- Add unit test for CRD validation of numaflow controller
- Verified in local kind cluster
=> Add unit test for crd validation

internal/controller/numaflowcontrollerrollout_controller.go
Refactor the git-ops sync logic in `NumaflowControllerRollout` to make the code more clear.
Existing tests and verified in a local cluster
=> chore: refactor sync logic in ControllerRollout to be more clear

config/crd/kustomization.yaml, config/install.yaml
Since Numaplane is managing Numaflow, it is a dependency for sure. This PR includes the installation process with the Numaflow minimal CRDs.  If the destination environment already have Numaflow installed then this is just a noop. But it will be helpful for clusters that don't. 
Verified in a local cluster
=> Install Numaflow CRDs as a depenency

internal/controller/isbservicerollout_controller_test.go, internal/controller/numaflowcontrollerrollout_controller.go, internal/controller/numaflowcontrollerrollout_controller_test.go, internal/controller/pipelinerollout_controller_test.go, internal/controller/suite_test.go
Fixes #19 
Enabled watching of Deployment resource in Numaflow Controller Rollout controller and updated unit test to test reconciliation logic.
Tested manually and via unit tests that making changes to the Deployment resource owned by the NumaflowControllerRollout will auto heal by undoing the changes.
=> Numaflow Controller Rollout Auto Healing

.github/workflows/release.yml
Incorporating release.yml from the previous repo over here.
This basically builds and deploys a Numaplane Controller image whenever:
- there's a new Git tag starting with "v"
- there's a change to the "main" branch
- there's a change to a branch starting with "dev-", which enables me to test a PR like this one (note its branch name)
Given this branch starts with "dev-", I was able to verify that a corresponding Docker tag got pushed [here](https://quay.io/repository/numaproj/numaplane-controller?tab=tags)
=> Release automation - automatically build and push images to quay.io

config/install.yaml, config/rbac/role.yaml, internal/controller/isbservicerollout_controller.go, internal/controller/isbservicerollout_controller_test.go, internal/util/kubernetes/kubernetes.go
Fixes #54 
- Create PodDisruptionBudget for each ISBSVC controller
Tested in local kind cluster
```bash
$ kubectl get poddisruptionbudgets -A                                                        macos-P9DJ3XY0QL: Tue Jun 25 16:54:47 2024
NAMESPACE           NAME        MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
example-namespace   my-isbsvc   N/A             1                 1                     30m
---------------------------
$ kubectl get po -A                                                                          macos-P9DJ3XY0QL: Tue Jun 25 16:55:00 2024
NAMESPACE            NAME                                            READY   STATUS    RESTARTS        AGE
example-namespace    isbsvc-my-isbsvc-js-0                           3/3     Running   0 …
```
=> feat: Create PodDisruptionBudget for each ISBSVC controller

internal/controller/numaflowcontrollerrollout_controller_test.go, internal/controller/suite_test.go
Fixes #46 
- Add unit test for deletion of numaflow controller rollout and it's child resource
- Verified in local kind cluster via running `make test`
=> Add unit test for deletion of numaflow controller rollout

internal/util/logger/logger.go
Fixes #89 
Moved code which shares globals to a place that would only be called once on startup.
Ran code, temporarily added a print statement to make sure it did the right thing
=> move code shared between goroutines to a central location in logger

internal/controller/config/config.go, internal/controller/isbservicerollout_controller.go, internal/controller/numaflowcontrollerrollout_controller.go, internal/controller/pipelinerollout_controller.go, internal/controller/suite_test.go, internal/util/kubernetes/config_watcher.go, internal/util/kubernetes/config_watcher_test.go, internal/util/kubernetes/kubernetes.go, internal/util/logger/base_logger.go, internal/util/logger/logger.go
Currently, we can ask the ConfigManager for the latest version of the ConfigMap. This works when we have a goroutine that's running that needs to get the latest and greatest values.
For cases in which we have some persistent state that's created based on value(s) in the ConfigMap, it could be nice to have a callback called to update that state.
This PR takes care of updating the Base Logger used by Numaplane through a callback.
Other remaining cases include:
- updating the `includedResources` passed to gitops-engine
- updating the Log Level that gitops-engine is using
While running, updated LogLevel=4 (debug) and observed that take effect in the log
=> Add callback functionality for the numaplane-controller-config ConfigMap

internal/controller/pipelinerollout_controller.go
Fixes #115 
`PipelineRollout.Reconcile()` is using a queue with a [default Controller Rate Limiter](https://github.com/numaproj/numaplane/blob/main/internal/util/queue.go#L20) which does exponential backoff. `Reconcile()` was adding to this queue calling `queue.AddRateLimited()`. If `Reconcile()` is called too many times in a row, the PipelineRollout gets delayed further and further.
After thinking about it, I don't think we need to add any delays for the initial reconciliation. 
Removing this seems to resolve the issue, based on @afugazzotto's testing.
=> remove rate limiting from initial PipelineRollout.Reconcile() call

internal/controller/isbservicerollout_controller.go, internal/controller/numaflowcontrollerrollout_controller.go, internal/controller/pipelinerollout_controller.go, internal/controller/shared.go, tests/manifests/kustomization.yaml
- On status update error, requeue the reconcile key to retry.
- BugFix on kustomization file for following error:
```
> kubectl kustomize tests/manifests | sed 's@quay.io/numaproj/@quay.io/numaproj/@' | sed 's/numaplane-controller:latest/numaplane-controller:latest/' | kubectl apply -f -
error: merging from generator &{0xc0013029c0 <nil>}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", Kind:"ConfigMap", isClusterScoped:false}, Name:"numaflow-controller-definitions-config", Namespace:"numaplane-system"} does not exist; cannot merge or replace
```
=> Status Update Error Requeue and Bug Fix

internal/controller/isbservicerollout_controller.go, internal/controller/numaflowcontrollerrollout_controller.go, internal/controller/pipelinerollout_controller.go, internal/controller/shared.go, tests/manifests/kustomization.yaml
Removed RequeueAfter from controllers on status update error and fixed bug with deploying Numaflow Controller config definitions.
=> Remove RequeueAfter and fix Numaflow Controller config definitions bug

Dockerfile
Yes
Fixes https://github.com/numaproj/numaplane/issues/82
According to the quay.io scan, the vulnerability was caused by the layer that was copying Helm into the Docker image. I have upgraded the Helm version to the recent v3.15.3 in the Dockerfile, which seems to have fixed the issue.
The Quay.io scanner does not show the security vulnerability anymore. There are two unknown security issues that I still need to work on.
=> Fixing security vulnerabilities Present in Quay.io

internal/controller/pipelinerollout_controller.go, pkg/apis/numaplane/v1alpha1/pipelinerollout_types.go
Fixes #114 
Mark pipeline rollout status to unpaused if a pipeline is not in pausing state (only on running or succeeded).
Unable to fully test at this time due to auto-healing enabled and not excluding changes to the lifecycle field. Was able to test by setting the lifecycle field in the rollout directly and then removing it.
=> Set pipeline pausing condition back to False after resuming a pipeline

config/install.yaml, config/rbac/kustomization.yaml, config/rbac/numaplane-aggregate-to-admin.yaml, config/rbac/numaplane-aggregate-to-edit.yaml, config/rbac/numaplane-aggregate-to-view.yaml
Introduces aggregate roles for admin, editor and viewer.
These follow the same formatting as Numaflow's roles defined [here](https://github.com/numaproj/numaflow/tree/main/config/cluster-install/rbac/controller-manager)
Ran `make start` to see that roles have been created properly
=> feat: introduce aggregate roles

config/samples/numaplane.numaproj.io_v1alpha1_numaflowcontrollerrollout.yaml, internal/controller/isbservicerollout_controller.go, internal/controller/numaflowcontrollerrollout_controller.go, internal/controller/pause.go, internal/controller/pause_requester.go, internal/controller/pipelinerollout_controller.go
Fixes #163 - Address prior PR comments
Fixes #174 - Use Pipeline's `ChildResourcesHealthy` condition to determine if Pipeline is still being reconciled
This addresses the following comments:
- [mark NumaflowControllerRollout unhealthy if Deployment doesn't exist](https://github.com/numaproj/numaplane/pull/125/files#r1697647636)
- [consolidate ](https://github.com/numaproj/numaplane/pull/125#discussion_r1698820989)`allPipelinesPaused()` function between NumaflowControllerRollout reconciler and ISBServiceRollout reconciler
- [improve readability](https://github.com/numaproj/numaplane/pull/125#discussion_r1698819003) in the NumaflowControllerRollout.reconcile() function
Note that I have decided to go for simplicity as far as the Pause Module. I have condensed the NumaflowController pause …
=> Pause feature - address remaining comments and more

config/install.yaml, config/manager/kustomization.yaml, config/manager/usde-config.yaml, internal/common/common.go, internal/controller/config/config.go, internal/controller/numaflowcontrollerrollout_controller.go, internal/controller/suite_test.go, internal/util/kubernetes/config_watcher.go, internal/util/kubernetes/config_watcher_test.go
Fixes #175 
Added ConfigMap for USDE Milestone 1. The ConfigMap is watched using the config watcher and the `numaplane.numaproj.io/config` label.
Added unit tests to ensure correct config loading.
=> USDE Config

cmd/main.go, config/install.yaml, config/rbac/role.yaml, internal/controller/isbservicerollout_controller.go, internal/controller/numaflowcontrollerrollout_controller.go, internal/controller/pipelinerollout_controller.go, internal/controller/suite_test.go, internal/util/kubernetes/unstructured_util.go, pkg/apis/numaplane/v1alpha1/const.go
Fixes #153 
- Record event for ISBServiceRollout, PipelineRollout and NumaflowControllerRollout
=> Add event recorder for ISBService, Pipeline and NumaflowController Rollout

internal/controller/monovertexrollout_controller.go, internal/controller/monovertexrollout_controller_test.go, internal/util/metrics/metrics.go
Fixes #195 
Exposes metrics for MonoVertexRollouts.
Tested locally that metrics were being emitted when a sample MonoVertexRollout was created.
Added unit test and ran `make test`
=> feat: add metrics for MonoVertexRollouts

config/install.yaml, config/samples/numaplane.numaproj.io_v1alpha1_numaflowcontrollerrollout.yaml, go.mod, go.sum, tests/manifests/default/controller_definitions.yaml
Adding the controller definition for `v1.3.0` which is the most recent Numaflow version that includes monovertices.
Ran `make start` to update local cm and `make test` to verify tests still work using this definition.
Created sample rollouts to see that the resources were created and functioned properly using this new definition.
=> feat: add numaflow controller definition for v1.3.0

config/samples/kustomization.yaml, config/samples/namespace-level-config.yaml, internal/common/common.go, internal/controller/config/config.go, internal/usde/usde.go, internal/util/kubernetes/config_watcher.go
Fixes #177 
Added a namespace-level ConfigMap users can use to add user-related customization parameters. Modified the config watcher to look for ConfigMaps in all namespaces and handle only those of interest based on labels and the namespace they are in.
Manually tested.
=> feat: User Strategy in Namespace-level ConfigMap

internal/util/util.go, internal/util/util_test.go
In order to test whether we need to update our Pipeline or ISBService based on the Rollout spec, we need to compare it with the one we get back from Kubernetes API Get() call. After the Pipeline or ISBService is created and reconciled, this value is the one that Numaflow Controller would have written back [when it did an Update()](https://github.com/numaproj/numaflow/blob/v1.3.0/pkg/reconciler/pipeline/controller.go#L90) as part of adding the Finalizer. Since Numaflow Controller would Unmarshal the JSON into a `Pipeline`struct and then Marshal it back into JSON to do the Update, this means that empty values can get written in. 
Previously, I was only ignoring these empty values:
- reference=nil
- map=empty 
- slice=empty
But I also need to ignore empty string, numeric = 0, and bool=false. …
=> fix: comparison of 2 JSON-derived maps requires ignoring keys with empty string, int, and bool values

hack/update-codegen.sh
`make codegen` seeing the following errrors,
```
rm: cannot remove '/tmp/tmp.xFtU2ZYXQs/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/pkg/tool/linux_amd64/cover': Permission denied
rm: cannot remove '/tmp/tmp.xFtU2ZYXQs/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/pkg/tool/linux_amd64/vet': Permission denied
rm: cannot remove '/tmp/tmp.xFtU2ZYXQs/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/pkg/tool/linux_amd64/covdata': Permission denied
```
This is caused by `generate-internal-groups.sh` is deprecated,
```
github.com/numaproj/numaplane/pkg/client '' github.com/numaproj/numaplane/pkg/apis numaplane:v1alpha1 --go-header-file hack/boilerplate.go.txt
WARNING: generate-internal-groups.sh is deprecated.
WARNING: Please use …
```
=> fix: `generate-internal-groups.sh` is deprecated.

Makefile, internal/controller/isbservicerollout_controller_test.go, internal/controller/pause_requester.go, internal/controller/pipelinerollout_controller.go, tests/e2e/common.go, tests/e2e/functional_test.go, tests/e2e/isbservice.go, tests/e2e/monovertex.go, tests/e2e/numaflowcontroller.go, tests/e2e/pipeline.go, tests/e2e/suite_test.go, tests/manifests/default/controller_definitions.yaml
Fixes #230 
1. I don't pause pipelines if they're "Failed"
2. I can update the pipeline spec without waiting for a "Failed" pipeline to be "Paused"
3. I can update NumaflowController and ISBService specs if Pipelines are either "Paused" or "Failed"
1. unit test checks ISBService (same code is used for Numaflow Controller so presumably that is being verified at the same time)
2. manually tested this sequence: create bad pipeline which failed validation; attempted to update failed pipeline with a change which didn't fix the problem; updated failed pipeline by fixing the validation error
3. manually tested updating ISBServiceRO and NCRO while pipeline was failed 
Was accidentally checking the `PipelineRollout.Conditions` rather than `Pipeline.Conditions` when waiting for the Pipeline to be …
=> fix: checking Pipeline conditions for PPND, plus don't pause failed pipelines

tests/e2e/common.go, tests/e2e/functional_test.go
Fixes #96 
Adds a common function to get a specific condition from a rollout's array of condition to then check the status of it.
For our e2e tests, we are checking the `ChildResourcesHealthyCondition` for all rollouts and extra for PipelineRollout the `PipelinePausedOrPausing` condition to be sure they are true or false in the correct cases.
TODO: We will want to include an env variable to signify when dataLossPrevention is enabled. This way we will appropriately check that pipelines are being paused during rollout updates.
```
func getRolloutCondition(conditions []metav1.Condition, conditionType apiv1.ConditionType) metav1.ConditionStatus {
for _, cond := range conditions {
if cond.Type == string(conditionType) {
return cond.Status
}
}
return metav1.ConditionUnknown
}
```
Ran `make …
=> test: check rollout conditions in e2e tests

internal/controller/monovertexrollout_controller.go
`MonoVerticesSyncFailed` metric didn't have any calls to increment it thus rendering it unhelpful as a metric.
Added call to increment this in appropriate place.
=> fix: MonoVerticesSyncFailed metric wasn't being incremented

internal/controller/isbservicerollout_controller.go, internal/controller/isbservicerollout_controller_test.go, internal/controller/monovertexrollout_controller.go, internal/controller/monovertexrollout_controller_test.go, internal/controller/numaflowcontrollerrollout_controller.go, internal/controller/numaflowcontrollerrollout_controller_test.go, internal/controller/pipelinerollout_controller.go, internal/controller/pipelinerollout_controller_test.go, internal/controller/suite_test.go, internal/util/kubernetes/unstructured_util.go, internal/util/kubernetes/unstructured_util_test.go, internal/util/metrics/metrics.go, tests/common/util.go, tests/e2e/functional_test.go, tests/e2e/isbservice.go, tests/e2e/monovertex.go, tests/e2e/numaflowcontroller.go, tests/e2e/pipeline.go
1. the `Update()` function in the controller-runtime framework always returns the new object with the correct resourceVersion in it (as mentioned in [this](https://medium.com/@timebertt/kubernetes-controllers-at-scale-clients-caches-conflicts-patches-explained-aa0f7a8b4332) article). I wanted to do the same thing for our dynamic client Update functions. This way if we call it consecutively, we are unlikely to have any resource version conflicts that cause us to return an error. **Verified this by:** writing a unit test for it to confirm the updated resourceVersion gets returned from an `UpdateCR()` call and that we can make a subsequent call to `UpdateCR()`.
2. I noticed that we were using the dynamic client to update the Rollout CRs, which wasn't necessary, so I changed it to use the …
=> feat: support consecutive Updates to our dynamic objects; also remove use of dynamic client for Rollouts (not needed)

internal/controller/pipelinerollout_controller.go, internal/controller/pipelinerollout_controller_test.go
Fixes #252 
This PR returns the reconciliation error when a pipeline with the same name already exist without a pipeline Rollout manage it. So the error is recorded by the metrics via the common error handler.
`make test`
=> fix: return error when a pipeline with the same name already exist without a pipeline Rollout manage it

internal/common/common.go, internal/controller/pipelinerollout_controller.go, internal/controller/pipelinerollout_controller_test.go
Fixes #254
This PR adds the label to the pipelines managed by numaplane, to quickly locate the Pipelines of a given PipelineRollout. This will be needed when there could be multiple pipelines associate with a pipelineRollout.
`make test`
=> feat: add a label to identify all Pipelines of a given PipelineRollout

.github/workflows/ci.yaml, Makefile, tests/e2e/common.go, tests/e2e/functional_test.go, tests/e2e/isbservice.go, tests/e2e/numaflowcontroller.go, tests/e2e/pipeline.go, tests/e2e/suite_test.go
Fixes #259 
This pull request introduces the DATA_LOSS_PREVENTION environment variable. When this is set, the user will be able to:
- run make start to install the manifests that set the `dataLossPrevention` flag to `true`
- run make test-e2e to run specific cases to check that resources are pausing when being updated (PPND)
With this change, we are also able to split the currently long e2e test run on the Github CI into two separate runs using a matrix. These two runs are for when this dataLossPrevention flag is enabled or not to accurately test functionality.
Modify Makefile to use DATA_LOSS_PREVENTION flag to install pause manifests.
e2e tests now includes logic that is only checked when this environment variable is set.
Changed the update Pipeline e2e test to be a more substantial …
=> test: add environment variable to enable dataLossPrevention for e2e testing

tests/e2e/common.go, tests/e2e/functional_test.go, tests/e2e/pipeline.go
Function in test that was supposed to be checking for a certain number of vertices running wasn't using the parameter passed in. Also, since the test switches from using 2 to 3 vertices, need to pass in 3 once the spec gets changed.
=> fix: functional test for checking correct number of pipeline vertices running

internal/controller/isbservicerollout_controller.go, internal/controller/numaflowcontrollerrollout_controller.go
Fixes #245 
If dataLossPrevention is enabled and there are pipelines that are not owned by a PipelineRollout in a namespace, when updating a NumaflowController/ISBServiceRollout they would wait for this pipeline to pause that never would. This is because this pipeline is never told to pause (intended) and the controllers for each rollout just list pipelines in the namespace to watch.
We change this query for pipelines in the namespace to check that they are owned by a PipelineRollout:
```
kubectl get pl -n {namespace} -l numaplane.numaproj.io/pipeline-rollout-name
``` 
Checked locally that updates on a NumaflowController and ISBService rollout both succeeded with a unowned pipeline existing in the namespace.
=> fix: nc/isbservice rollouts will not wait for unowned pipelines to pause

internal/controller/monovertexrollout_controller.go, internal/util/metrics/metrics.go, pkg/apis/numaplane/v1alpha1/monovertexrollout_types.go, pkg/apis/numaplane/v1alpha1/status_types.go
Fixes: https://github.com/numaproj/numaplane/issues/233
Add rollout health metrics for monovertex
- verified in local k8s cluster
```bash
numaplane_monovertex_rollout_health{intuit_alert="true",monovertex="my-monovertex",namespace="example-namespace"} 1
```
=> feat: Add health metrics for monovertex

tests/e2e/isbservice.go
I've seen 2 CI runs fail recently (with `dataLossPrevention=false`) due to the 2 minute timeout occurring when updating the isbsvc, waiting for it to be healthy and have its health incorporated into the ISBServiceRollout's health. I ran it locally and it worked fine, so I'm thinking it's just that updating the isbsvc takes awhile. Increasing the time to 3 minutes.
Ran 5 times in a row through the CI and it passed each time.
=> fix: increase timeout for isbsvc being healthy

internal/common/common.go, internal/controller/pipelinerollout_controller.go, internal/controller/pipelinerollout_controller_test.go
Fixes #272 
Added the label `numaplane.numaproj.io/upgrade-state: promoted` to uniquely identify the deployed/promoted pipeline associate with a PipelineRollout, together with label `numaplane.numaproj.io/pipeline-rollout-name: pipeline-rollout-name`, instead of using the PipelineRollout name. And the `upgrade-state` label can only be in `promoted` or `in-progress`, the later should only be used for no down time upgrade feature.
`make test`
=> feat: add a label to identify the promoted/deployed pipeline for a pipelineRollout

tests/e2e/suite_test.go
Was getting an error trying to make the directory - need to delete previous directory first
I thought it was better to delete the previous directory (as opposed to skipping the `MkDir()`) so as to remove any previous outputs and start clean.
=> fix: delete old outputs directory before creating new one

config/install.yaml, tests/e2e/common.go, tests/e2e/functional_test.go
I originally changed the polling for many of our calls to 1 second out of fear that there would be a rate limiting issue that would cause false failures.
However, I am seeing some intermittent CI failures due to not catching the pausing fast enough, so we need to make sure we check frequently.
So, thinking to change back to 10ms until we see an actual case where this fails due to rate limiting. It may be that 10ms is fine (I tried looking up what the default rate limit would be but couldn't easily find that information).
=> fix: change polling interval in e2e test back to 10ms

tests/e2e/common.go, tests/e2e/functional_test.go
Fixes #301
We were previously not collecting `job` pod logs before. This was causing issues when creating logs for both PipelineRollout and MonoVertexRollout pods. Therefore, we have now included them which has fixed the issue.
Running `make test-e2e` locally with both failing and successful tests.
Running on Github CI with a failing test to view artifacts output properly - https://github.com/numaproj/numaplane/pull/303/commits/9106f8fe6302b73ff4c09158b0ef78e97d2ccbbf
=> fix: pod artifacts were not populating properly. Fixes #301

internal/controller/pipelinerollout_controller.go
Fixes #304 
This PR Utilize the `promoted` label to identify the running pipeline managed by a PipelineRollout. If such pipeline does not exist, the name should be calculated using the `NameCount` suffix.
`make test`
=> feat: use the `promoted` label to identify the running pipeline

tests/e2e/functional_test.go
There are occasional CI e2e failures due to there being no persistence set for the isbsvc. This means that if an isbsvc Pod goes down at the wrong time, information as far as buffers and buckets can be lost.
This sets persistence for the initially created isbsvc and also after it gets updated.
This is the result of `kubectl get isbsvc -o yaml` during the test:
```
- apiVersion: numaflow.numaproj.io/v1alpha1
kind: InterStepBufferService
metadata:
creationTimestamp: "2024-10-01T01:54:55Z"
finalizers:
- isbsvc-controller
generation: 2
name: test-isbservice-rollout
namespace: numaplane-system
ownerReferences:
- apiVersion: numaplane.numaproj.io/v1alpha1
blockOwnerDeletion: true
controller: true
kind: ISBServiceRollout
name: test-isbservice-rollout
uid: 170afb1a-9f8c-4e3b-abba-0dca57a4569d …
```
=> fix: adding persistence to isbsvc used in functional test

tests/e2e/functional_test.go, tests/e2e/isbservice.go, tests/e2e/pipeline.go, tests/e2e/suite_test.go
Fixes #311 
Adds `Vertex` and `StatefulSet` to artifact output by keeping track of resource changes documented by `kubectl get -o yaml`.
Ran `make test-e2e` locally to view artifacts output properly.
Running CI with bad test to view artifact output - https://github.com/numaproj/numaplane/pull/312/commits/59015758e2ebeed072f6934f3033e077251a9cd1
=> test: adding Vertices and StatefulSets to artifact output

internal/controller/pipelinerollout_controller.go, internal/controller/pipelinerollout_controller_test.go, internal/controller/pipelinerollout_ppnd.go, tests/e2e/functional_test.go, tests/e2e/pipeline.go
This makes it so that we no longer require to be paused simply because pipeline is still reconciling. 
The original process of updating was:
1. pause pipeline
2. wait for it to be paused
3. apply new pipeline spec with `desiredPhase=Paused`
4. wait for pipeline change to be reconciled based on `pipeline.ObservedGeneration` and pipeline Conditions, which indicate whether daemon, vertices, side inputs are fully reconciled
5. set `desiredPhase=Running`
I have to remove step 4 because it's impossible to know based on Pipeline Conditions whether Pipeline is in fact still "progressing" or failed. This becomes clear when we actually deploy a bad pipeline.
Why I think this is okay to remove: After the Pipeline has been paused, it goes down to 0 vertices. After we apply the spec, Numaflow …
=> fix: don't wait for pipeline to finish updating because we can't distinguish failure from progressing

tests/e2e/pipeline.go
While Sidhant is looking at [this](https://github.com/numaproj/numaflow/issues/2115) issue, hopefully we can unblock the CI, which seems to be failing frequently, by commenting out the check for "DrainedOnPause=true". 
Behavior we are seeing is that the pause is happening but after the 30 second timeout, so `DrainedOnPause` isn't being set to true.
Have run CI 4 times and it passed each time
=> fix: unblock CI by commenting out test for drainedOnPause

internal/common/common.go, internal/controller/isbservicerollout_controller.go, internal/controller/isbservicerollout_controller_test.go, internal/controller/numaflowcontrollerrollout_controller.go, internal/controller/pause_requester.go, internal/controller/pipelinerollout_controller_test.go, internal/controller/pipelinerollout_ppnd.go
Fixes: https://github.com/numaproj/numaplane/issues/295
I have actually written the ArgoCD extension locally. I have added to it the capability to apply an "allow-data-loss" annotation to the PipelineRollout while the PipelineRollout is in the middle of the PPND Upgrade strategy, and to remove it any time that the annotation is present, whether or not in the middle of PPND Upgrade.
This introduces that annotation. The annotation is observed whether the Pipeline is pausing due to its own need to update or if it's pausing because the Numaflow Controller or isbsvc are updating.
Tested end to end with ArgoCD. Tested with a slow Pipeline in the middle of draining, in which I added the annotation in the middle of "Pausing" - it did not complete the drain and updated the spec and went back to …
=> feat: Allow pipeline to be temporarily marked to allow data loss

tests/e2e/functional_test.go
Fixes #314 
MonoVertex currently ends up unhealthy in testing since we are updating the source image to an unstable and outdated version that is incompatible with Numaflow. This changes it to update to the most stable Python image instead.
Ran `make test-e2e` locally and checked MonoVertex logs to see that it is still healthy.
=> test: change MonoVertexRollout update test to be more stable

internal/controller/pipelinerollout_controller.go, internal/controller/pipelinerollout_controller_test.go, internal/controller/pipelinerollout_progressive.go, pkg/apis/numaplane/v1alpha1/pipelinerollout_types.go
Fixes #225
Pipeline No Downtime upgrade which creates a second pipeline when upgrade strategy is `progressive`. A follow up  will do clean up for the old pipeline, e.g. pause the pipeline and delete after drain is completed.
`make test`
Run in local cluster, apply a namespace config to set the upgrade strategy to `progressive` and see a new pipeline running and `PipelineProgressiveUpgradeSucceed` in the PipelineRollout to be true.
=> feat: Pipeline No Downtime Upgrade

internal/common/common.go, internal/controller/pipelinerollout_controller.go, internal/controller/pipelinerollout_controller_test.go, internal/controller/pipelinerollout_progressive.go, internal/util/kubernetes/unstructured_util.go, internal/util/kubernetes/unstructured_util_test.go
Fixes #334 
This PR adds the logic for draining the old pipeline and delete drained pipeline during clean up.
`make test`
Verified in local cluster with edit the pipeline rollout spec and saw the old pipeline gets drained and deleted.
=> feat: Pipeline No Downtime Upgrade Clean Up

internal/controller/pipelinerollout_controller.go, internal/util/metrics/metrics.go
Fixes #309 
Added namespace to the `numaflow_pipeline_paused_seconds` metric.
Forwarded port 8080 of the numaplane-controller-manager pod and looked at the metric `numaflow_pipeline_paused_seconds` after pausing the pipeline by setting the `lifecycle.desiredPhase` to `Paused` in the PipelineRollout.
=> fix: added namespace to metric numaflow_pipeline_paused_seconds

config/crd/bases/numaplane.numaproj.io_numaflowcontrollerrollouts.yaml, config/install.yaml, internal/controller/numaflowcontrollerrollout_controller.go, internal/controller/numaflowcontrollerrollout_controller_test.go, pkg/apis/numaplane/v1alpha1/numaflowcontrollerrollout_types.go, tests/manifests/default/controller_def_1.3.3-copy1.yaml, tests/manifests/default/controller_def_1.3.3.yaml
Added instanceID to the NumaflowControllerRollout spec and templated the definitions config to include the instanceID.
Manually tested that multiple instances are deployed and "tagged" (resource name suffixed) by the instanceID defined in the NumaflowControllerRollout spec. Added unit tests for func `resolveManifestTemplate`.
=> feat: allow for multiple instances of the NumaflowController

internal/common/common.go, internal/usde/usde.go, internal/usde/usde_test.go
This updates the USDE `ResourceNeedsUpdating()` call to compare not just specs but also metadata (Labels and Annotations).
Note that this code will be improved later, but for now what it does is:
- consider just the "Instance" annotation as one which requires PPND or Progressive (I think PPND and Progressive both apply if you're changing which Controller to use)
- if any other Label or Annotation changes, return DirectApply
Then take the most conservative strategy returned from comparing `Metadata` and from comparing `Spec`.
Note that the caller merges the new and existing child definitions together to create the updated "new definition" (i.e. existing Labels/Annotations with overriding Labels/Annotations coming from the Rollout definition). Therefore, it should work to compare that "new …
=> feat: Incorporate metadata into the USDE check

internal/controller/isbservicerollout_controller.go, internal/controller/monovertexrollout_controller.go
The names `key` and `val` were reversed
=> fix: reverse use of "key" and "val" naming in map traversal

internal/controller/numaflowcontrollerrollout_controller.go, internal/controller/numaflowcontrollerrollout_controller_test.go, tests/manifests/default/controller_def_1.3.3-copy1.yaml, tests/manifests/default/controller_def_1.3.3.yaml
Added instanceID to configmap and created instance labels.
Manual tests:
1. create 2 NumaflowControllerRollout resources with different instanceIDs
2. create 1 ISBServiceRollout resource with annotation `numaflow.numaproj.io/instance: "1"` linking it to the instance 1 of the NumaflowController
3. verify that NFC instance 1 reconciles the ISBSvc while the other instance skips reconciliation (seen by enabling debug logs).
=> fix: added instanceID to configmap and created instance labels

config/samples/numaplane.numaproj.io_v1alpha1_monovertexrollout.yaml, config/samples/numaplane.numaproj.io_v1alpha1_numaflowcontrollerrollout.yaml, internal/controller/monovertexrollout_controller.go, internal/controller/monovertexrollout_controller_test.go
Fixes #353
When reconciling a MonoVertexRollout object, use the `replicas` from existing MonoVertex object if it has.
Created a MonoVertexRollout object, manually scaled the orchestrated MonoVertex replicas, the numaplane controller did reconcile the watched notification, but the `replicas` value in the MonoVertex object remained unchanged.
=> chore: ignore mvtx replicas if it exists

cmd/main.go, internal/common/common.go, internal/controller/common_test.go, internal/controller/isbservicerollout_controller.go, internal/controller/isbservicerollout_controller_test.go, internal/controller/monovertexrollout_controller.go, internal/controller/numaflowcontrollerrollout_controller.go, internal/controller/numaflowcontrollerrollout_controller_test.go, internal/controller/pause.go, internal/controller/pipelinerollout_controller.go, internal/controller/pipelinerollout_controller_test.go, internal/controller/pipelinerollout_ppnd.go, internal/controller/pipelinerollout_progressive.go, internal/controller/suite_test.go, internal/util/kubernetes/dynamic_clientset.go, internal/util/kubernetes/unstructured_util.go, internal/util/kubernetes/unstructured_util_test.go
Fixes #344
- MonoVertex Watch should be Unstructured
- Remove redundant code from unstructured_util
- Prevent calls to REST API when getting Status of child
- Set DynamicClient at once, instead of generating it in each API call
Verified in local kind cluster
=> fix: refactor unstructured_util and reduce k8s api call

internal/controller/isbservicerollout_controller_test.go, internal/controller/numaflowcontrollerrollout_controller_test.go, internal/controller/pipelinerollout_controller_test.go
I wanted to make the test cases within the PPND unit test for isbsvc isolated so that each one is not dependent on the one that occurred before. I noticed that we weren't setting the initial `UpgradeInProgress` value, so when I'd tried to just test one of the cases in the middle it failed, but then it passed when I uncommented out the others. 
Also, made a couple of other minor mods to other PPND tests.
Adding initial `UpgradeInProgress` makes it so that I can comment/uncomment them separately (I verified this).
=> chore: create better isolation between isbsvc test cases by adding initial UpgradeInProgress value

internal/controller/isbservicerollout_controller.go, internal/controller/isbservicerollout_controller_test.go, internal/controller/monovertexrollout_controller.go, internal/controller/monovertexrollout_controller_test.go, internal/controller/numaflowcontrollerrollout_controller.go, internal/controller/numaflowcontrollerrollout_controller_test.go, internal/controller/pipelinerollout_controller.go, internal/controller/pipelinerollout_controller_test.go, internal/util/metrics/metrics.go
Renamed the names used in the code as well as the metric names for a few things:
- our counters were named after the child (i.e. `pipeline`) when in the code they really seemed to represent the counts of Rollouts
- changed the names of the counters representing "syncs" and "sync errors" to better describe what they represent
=> fix: Metrics rename

internal/controller/pipelinerollout_controller.go, internal/controller/pipelinerollout_ppnd.go, internal/util/metrics/metrics.go
Fixes #240 
Modifies the pipelinePausedSeconds metric to distinguish between if the pause is user or system requested.
Refactors logic used in PPND logic for Pipeline to determine if the pause is spec based or not.
Tested locally by pausing two different rollouts with a spec based pause and an update that would cause PPND.
Verified that the metrics updated properly for the right case.
```
numaflow_pipeline_paused_seconds{intuit_alert="true",name="my-pipeline",namespace="example-namespace",pause_type="user_pause"} 2.265524783
numaflow_pipeline_paused_seconds{intuit_alert="true",name="other-pipeline",namespace="example-namespace",pause_type="system_pause"} 2.224975533
```
=> feat: pause metrics distinguish between user and system requested pauses

Makefile, hack/numaflow-controller-def-generator/def-configmap.yaml, hack/numaflow-controller-def-generator/kustomization.yaml, hack/numaflow-controller-def-generator/numaflow-controller-def-generator.sh, tests/manifests/default/controller_def_1.3.3.yaml
Fixes #373 
Created a script that uses kustomize and yq to generate a templated Numaflow controller definition manifest based on the latest version of the Numaflow numaspace-install manifest. The script can be called with an argument to generate a specified file or without an argument to generate the yaml file in the default controller definitions manifest directory (generated via `make start`).
Manual tests performed on the script (both with and without argument) and tested the generated yaml in a cluster to validate the generated configmap.
=> feat: generate a templated Numaflow controller definition manifest based on the latest version of the Numaflow numaspace-install manifest

internal/controller/config/config.go, internal/controller/config/usde_config.go, tests/manifests/default/config.yaml
I noticed we weren't printing anything when the configmaps change. I'm guessing people decided not to because there's a cyclical dependency caused if you try to use the logger, which depends on the `config` module. I decided to just add `fmt.Printf` statements in that case.
Second, I also noticed there were some outdated fields in the configmap we're applying when we run `make start` (from original Numaplane), so I removed them.
Updated ConfigMaps and verified I saw the changes reflected in the log.
=> chore: print message when configmaps change; remove outdated fields from configmap that's run locally

tests/e2e/common.go, tests/e2e/functional_test.go, tests/e2e/isbservice.go, tests/e2e/monovertex.go, tests/e2e/numaflowcontroller.go, tests/e2e/pipeline.go, tests/e2e/suite_test.go
Fixes #430 
Refactors watch logic for e2e tests to minimize code redundancy between every call. This is achieved by making the `writeToFile` function that they all share to write the `kubectl get -o yaml` output to the resulting files. We also can start up every watch before the suite starts as opposed to starting them when the resource is created.
Running `make test-e2e` and checking result artifacts.
=> feat: refactoring watch logic for e2e tests

internal/controller/common/numaflowtypes/pipeline.go, internal/controller/common/numaflowtypes/pipeline_test.go, internal/controller/pipelinerollout/pipelinerollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_controller_test.go
Improving code quality by having these function signatures match
- new unit tests plus existing unit test for `PipelineRolloutReconciler.ChildNeedsUpdating()` function
- existing e2e tests
=> chore: Make function signatures similar for WithDesiredPhase() and WithoutDesiredPhase()

internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/isbservicerollout/isbservicerollout_controller_test.go, internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller.go, internal/util/metrics/metrics.go
Fixes #425 
Hold the deletion of NumaflowControllerRollout util the dependent resource are deleted
Verified in local kind cluster.
Tested Scenario:
- Created NumaflowControllerRollout, ISBServiceRollout, PipelineRollout and MonovertexRollout
- Tried Deleting NumaflowControllerRollout - It got stuck in deleting as the dependent resources are still running and Numaplane controller started showing logs as below:
`{"level":"warn","numaflowcontrollerrollout":{"Namespace":"example-namespace","Name":"numaflow-controller"},"logger":"numaplane.controller-manager.numaflowcontrollerrollout-reconciler","caller":"numaflowcontrollerrollout/numaflowcontrollerrollout_controller.go:248","ts":"2024-11-30T16:15:59.713068342Z","msg":"Dependent resources are not deleted yet, requeue after 5 seconds"}`
- …
=> fix: Ensure NumaflowControllerRollout is not removed until dependent are deleted

tests/e2e/functional_test.go
Attempted fix to #435 
Apparently, newer version of Jetstream is more stable.
=> fix: update jetstream versions used in e2e

tests/e2e/common.go, tests/e2e/isbservice.go, tests/e2e/monovertex.go, tests/e2e/numaflowcontroller.go, tests/e2e/pipeline.go
Fixes #441 
Consolidated watch functions for collecting `kubectl get <resource> -o yaml` output by creating shared function.
Also updated `writeToFile` function to create filepath based on `Output` structure passed into it.
```
func watchResourceType(getWatchFunc func() (watch.Interface, error), processEventObject func(runtime.Object) Output) {
defer wg.Done()
watcher, err := getWatchFunc()
if err != nil {
fmt.Printf("Failed to start watcher: %v\n", err)
return
}
defer watcher.Stop()
for {
select {
case event := <-watcher.ResultChan():
if event.Type == watch.Modified {
output := processEventObject(event.Object)
err = writeToFile(output)
if err != nil {
return
}
}
case <-stopCh:
return
}
}
}
```
Running `make test-e2e` locally multiple times to check that resource logs are still being …
=> feat: consolidate watch functions into shared function

cmd/main.go, internal/controller/config/config.go, internal/controller/config/usde_config.go, internal/util/logger/logger.go
Fixes #129 
- Fix debug event logger
- Replace printf statement to zerolog 
Verified in local kubernetes cluster, attached the log file for reference
[numaplane.log](https://github.com/user-attachments/files/18093527/numaplane.log)
=> fix: Debug event logger and use zerolog instead of fmt

internal/controller/numaflowcontroller/numaflowcontroller_controller.go
Fixes #455 
During NumaflowController reconciliation, if a Deployment already exists for the NumaflowController and the new version differs from the current Deployment version, delete all the NumaflowController child resources and recreate them at the next reconciliation.
Executed unit tests and e2e tests.
Manually tested the following cases:
- going from a valid version to an invalid version and back to the previous valid version
- going from a valid version to an invalid version, then to a new valid version
- going from a valid version to a new valid version
- going from a version without instance labels to a version with instance labels
There should be no backward incompatibilities in these changes.
=> feat: NumaflowController update delete and recreate child resources

tests/e2e/common.go, tests/e2e/functional_test.go, tests/e2e/monovertex.go, tests/e2e/pipeline.go
Fixes #393 
Modifies `functional_test.go` to instead use a helper function `getPipelineName` or `getMonoVertexName` to get the child resource's name instead of outright using the constant we have previously used before. This is due to the Progressive strategy of updating rollouts eventually changing the instance of each child resource ie. `my-pipeline-0` will be `my-pipeline-1` after a successful update. 
We can achieve this currently by listing the resources with the label `numaplane.numaproj.io/upgrade-state=promoted` which there should only be 1 of with the correct label `numaplane.numaproj.io/parent-rollout-name`.
Running `make test-e2e` locally and passing multiple times. Double checking with CI now.
No compatibility errors as this is for end to end testing.
=> feat: update e2e tests to accommodate for progressive strategy

cmd/main.go, internal/controller/common/predicate_filters.go, internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/numaflowcontroller/numaflowcontroller_controller.go, internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_controller.go
Fixes https://github.com/numaproj/numaplane/issues/388
Add custom predicate filter which filter all the events other than "ResourceVersion" change and "SyncPeriod" event.
Reference taken from already open issue in controller-runtime: https://github.com/kubernetes-sigs/controller-runtime/issues/2355#issuecomment-2477548322
Verified on local Kubernetes cluster by setting the SyncPeriod time as 2 min, Numaplane is reconciling every resource every 2min.
=> fix: Configure SyncPeriod for reconcile at given interval of time

internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_controller.go, internal/util/metrics/metrics.go
Fixes https://github.intuit.com/oss-analytics/numa-manifest-generator/issues/148
Added `Phase` attribute to Rollout health metrics data
```bash
numaplane_isb_services_rollout_health{intuit_alert="true",isbservice="my-isbsvc",namespace="example-namespace",phase="Deployed"} 1
numaplane_pipeline_rollout_health{intuit_alert="true",namespace="example-namespace",phase="Deployed",pipeline="my-pipeline"} 1
numaplane_monovertex_rollout_health{intuit_alert="true",monovertex="my-monovertex",namespace="example-namespace",phase="Deployed"} 1
```
- It only affect on metrics dashboard for rollout health
=> fix: Add phase to health metrics for pipeline, monovertex and ISBService

tests/e2e/functional_test.go
Makes update to the e2e test case where we delete the rollout and check that the corresponding child resource is deleted. We previously would get the resource and check that it returned the correct error to indicate it doesn't exist. This requires having the resource's name which was previously a constant but is no longer the case with the new naming convention (ex. pipeline-0) for all resources. To remedy this, we can list the resources and verify that the returned list is empty.
Running `make test-e2e` locally and verifying that it is passing on the CI.
None.
=> fix: updated deletion test case to not require getting the child resource name

config/install.yaml, config/manager/usde-config.yaml, internal/controller/config/usde_config.go, internal/controller/config/user_config.go, internal/controller/isbservicerollout/isbservicerollout_controller_test.go, internal/controller/pipelinerollout/pipelinerollout_controller_test.go, internal/usde/usde.go, internal/usde/usde_test.go, internal/util/kubernetes/config_watcher.go, internal/util/kubernetes/config_watcher_test.go
Changed USDE config to include more than just data-loss fields (recreate and progressive fields).
This PR only includes the changes to modify the USDE config structure. Future PR will include changes to the logic to utilize those new configuration fields and to properly setup the configuration spec fields.
Manually tested that the USDE config structure is loaded correctly. Updated unit tests to reflect the new structure.
At this point, this PR should not cause backward incompatibility issues unless the USDE ConfigMap cannot be updated during upgrade.
=> feat: changed USDE config to include more than just data-loss fields

internal/controller/numaflowcontroller/numaflowcontroller_controller.go, internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller.go, internal/util/metrics/metrics.go
Fixes #TODO
Add phase to numaflowControllersHealth and numaflowControllerRolloutsHealth metrics
Verified in local kubernetes cluster.
```bash
numaflow_controller_health{intuit_alert="true",namespace="example-namespace",numaflowcontroller="numaflow-controller",phase="Deployed"} 1
numaflow_controller_rollout_health{intuit_alert="true",namespace="example-namespace",numaflowcontroller="numaflow-controller",phase="Deployed"} 1
```
=> fix: Add phase to numaflowControllersHealth and numaflowControllerRolloutsHealth metrics

.github/workflows/ci.yaml, Makefile, tests/e2e/common.go, tests/e2e/functional_test.go, tests/e2e/isbservice.go, tests/e2e/numaflowcontroller.go, tests/e2e/suite_test.go
Fixes #474 
Incorporates `progressive` strategy to e2e test matrix and redefines matrix to be 3 different runs: `no-strategy`, `pause-and-drain` and `progressive`
Running `make test-e2e` with `STRATEGY` variable set locally to verify change is working.
Checking that the CI's matrix is updated correctly to reflect new matrix.
None.
=> feat: add progressive to e2e test matrix

internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller.go, internal/util/metrics/metrics.go
Fixes https://github.com/numaproj/numaplane/issues/483
Add Numaflow controller version and name in metrics data.
```bash
numaflow_controller_rollouts_running{intuit_alert="true",name="numaflow-controller",namespace="example-namespace",version="1.3.3"} 1
```
=> fix: Add version and name of numalfow controller in metrics

internal/util/kubernetes/clientset.go
Add the Numaplane Clientset as one we can use. This can be used to get a live Numaplane resource from Kubernetes API rather than needing to only go through our controller-runtime client, which always goes to the cache first.
=> chore: add numaplane clientset

go.mod, go.sum
May fix: #497 
Apparently, this same test failure happened twice (which I can confirm to be an error in the test and not an error in numaplane functionality based on looking at the resource output), and both occurred after we updated the e2e test to use numaflow 1.4.0/1.4.2  [here.](https://github.com/numaproj/numaplane/pull/490/files)
Possible theory is that [this](https://github.com/numaproj/numaplane/blob/main/tests/e2e/pipeline.go#L177-L191) code could possibly fail if the PipelineSpec and PipelineStatus fields aren't compatible with the version of Numaflow that's running.
Since the test is using numaflow 1.4.x, I thought I'd try updating the numaflow package to match 1.4.2 at least, and see if we still get the intermittent e2e failure.
CI
I checked our non-test code, and the only …
=> chore: update imports to use latest numaflow (1.4.2)

config/samples/numaplane.numaproj.io_v1alpha1_monovertexrollout.yaml, tests/e2e/functional_test.go
The images that our sample MonoVertexRollout and our e2e test uses were not built to be multi-platform, so they result in Crash loop if run on arm64 architecture. (That may be fixed later.) Therefore, updating these to use images which are multi-platform.
Doing `kubectl apply` for the sample MonoVertexRollout and seeing it run successfully. 
Running the e2e test locally and seeing the MonoVertexRollout running successfully both at the beginning and end of the test.
N/A
=> fix: update monovertexrollout sample and e2e to use a monovertex with images that are multi-platform

internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller.go
The problem: When updating NumaflowControllerRollout, if Progressive strategy is set as preferred, we are doing Apply strategy, but we are still setting the `UpgradeInProgress` field to "Progressive" in the `NumaflowControllerRollout` and we are leaving it set there. This changes it so we don't set that at all.
Updated NumaflowControllerRollout. This applied the Numaflow Controller and did not set the `UpgradeInProgress` field.
none
=> fix: if Progressive is set, do Apply strategy for Numaflow Controller updates 

internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/isbservicerollout/isbservicerollout_progressive.go, internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/monovertexrollout/monovertexrollout_progressive.go, internal/controller/pipelinerollout/pipelinerollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_progressive.go
Just moving the `ChildNeedsUpdating()` function out of the .go files for progressive (for each Reconciler), because the function is not only used by the progressive code.
=> chore: move ChildNeedsUpdating() function since it's not just related to Progressive logic

internal/controller/common/rollout_controller.go, internal/controller/common/rollout_controller_test.go, internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/isbservicerollout/isbservicerollout_progressive.go, internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/monovertexrollout/monovertexrollout_progressive.go, internal/controller/pipelinerollout/pipelinerollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_progressive.go, internal/controller/progressive/progressive.go, internal/controller/progressive/progressive_test.go
Note: this PR makes no logic changes.
Previously, the whole idea of having an "upgrade-state" and also the idea of using that to garbage collect children was considered to be a "progressive" thing. Now that we are introducing the delete/recreate capability for child objects, we can use the same "recyclable" label value for performing that deletion and the same logic for performing the delete. 
This means we need to move the code related to updating that value and for updating the label altogether out of the progressive-specific code. 
Therefore, I am introducing a new interface called `RolloutController`, where all 4 of our Rollouts either implement them now or will in the future (`NumaflowControllerRollout` would be future for performing blue/green; the others already do). 
no logic was …
=> chore: introduce new RolloutController interface

tests/e2e/common.go, tests/e2e/functional_test.go, tests/e2e/isbservice.go, tests/e2e/monovertex.go, tests/e2e/numaflowcontroller.go, tests/e2e/pipeline.go
Fixes #528 
This PR largely breaks down the current functional test suite and moves the create/update/deletion functions for each respective rollout to their own file. These functions are now able to be used in different test suites we can build out for different upgrade strategies or any other cases that shouldn't require us to run the whole functional test.
We can further improve on this by introducing new shared functions but these should be sufficient to create new test suites now.
Running `make test-e2e` multiple times locally with no strategy and PPND. Using CI for final verification.
None.
=> feat: create reusable e2e functions

internal/common/common.go, internal/controller/config/config.go, internal/controller/config/config_test.go, internal/controller/ginkgo_suite_test.go, internal/controller/numaflowcontroller/numaflowcontroller_controller.go, internal/util/kubernetes/config_watcher.go, internal/util/kubernetes/config_watcher_test.go
Fixes https://github.com/numaproj/numaplane/issues/429
- Update `rolloutConfig` map for storing [namespace/version] as key with fullSpec as value
- While reading the data from `rolloutConfig` firstly check user specific namespace configmap if not found then use from "numaplane-system" namespace
- Verified on local kubernetes cluster by creating configmap in user namesapce
=> feat: Use controller definition configmap from user namespace

internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/numaflowcontroller/numaflowcontroller_controller.go, internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_controller.go, internal/util/metrics/metrics.go, pkg/apis/numaplane/v1alpha1/status_types.go
Fixes #TODO
- Update Pipeline, ISBService, MonoVertex, NumaflowController_rollout and NumaflowController health metrics according to below format:
```
// Example: Set the state to "deployed"
pipelineRolloutHealth.WithLabelValues("deployed",...).Set(1)
pipelineRolloutHealth.WithLabelValues("pending",...).Set(0)
pipelineRolloutHealth.WithLabelValues("failed",...).Set(0)
// Example: Change the state to "pending"
pipelineRolloutHealth.WithLabelValues("deployed",...).Set(0)
pipelineRolloutHealth.WithLabelValues("pending",...).Set(1)
pipelineRolloutHealth.WithLabelValues("failed",...).Set(0)
// Example: Change the state to "failed"
pipelineRolloutHealth.WithLabelValues("deployed",...).Set(0)
pipelineRolloutHealth.WithLabelValues("pending",...).Set(0) …
```
=> fix: Update Numaplane health metrics

internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/isbservicerollout/isbservicerollout_progressive.go, internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/monovertexrollout/monovertexrollout_progressive.go, internal/controller/pipelinerollout/pipelinerollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_progressive.go, internal/controller/progressive/progressive.go, internal/controller/progressive/progressive_test.go
Changes relative to comments on PR [540](https://github.com/numaproj/numaplane/pull/540):
- Updated scaling up/down logic and renamed shared functions
- Moved logic to perform scaling after creating the upgrading resource
- using PatchResource instead of UpdateResource
E2E and unit tests.
None.
=> chore: promoted MonoVertex/Pipeline scaling logic adjustments and fixes

.github/workflows/ci.yaml, internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/numaflowcontroller/numaflowcontroller_controller.go, internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_controller.go, tests/e2e/common.go
Fixes https://github.com/numaproj/numaplane/issues/510
- Set foreground deletion policy for pipeline, monovertex, isbService and Numaflow Controller
- Verified in local Kubernetes cluster
=> fix: Set foreground deletion policy for rollout deletion

internal/controller/pipelinerollout/pipelinerollout_controller.go, tests/e2e/ppnd-e2e/ppnd_test.go
Fixes #559 
By performing a `Get()` after adding the `foregroundDeletion` finalizer, we can eliminate the resource version conflict issue that occurs. 
Running the CI, it seems to pass all of the tests for confirming deletion has occurred.
However, @chandankumar4 will follow up with another PR to address our other CRDs and to do additional testing for different cases. 
N/A
=> fix: pipelinerollout deletion sequence

cmd/main.go, config/install.yaml, config/manager/controller-config.yaml, internal/controller/config/config.go, internal/controller/config/config_test.go, internal/util/logger/base_logger.go, internal/util/logger/logger.go, tests/config/testconfig.yaml, tests/config/testconfig2.yaml, tests/manifests/default/config.yaml, tests/manifests/special-cases/no-strategy/controller-config.yaml, tests/manifests/special-cases/progressive/controller-config.yaml
Fixes https://github.com/numaproj/numaplane/issues/43
- Define configmap LogLevel as user-friendly string, which supports: "ERROR", "WARN", "INFO", "DEBUG" and "VERBOSE"
- Yes, with this version `LogLevel` should be defined as string instead of `Number`
=> feat: Be able to define ConfigMap LogLevel as a user-friendly string

internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/numaflowcontroller/numaflowcontroller_controller.go, internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller.go
Fixes https://github.com/numaproj/numaplane/issues/567
- Fixed Rollout deletion sequence for isbService, MonoVertex and NumaflowController
- Fixes `areDependentResourcesDeleted` resources which are listing the child resources - Replaced Kind with Plural
=> fix: rollout deletion sequence

.github/workflows/ci.yaml, Makefile, internal/controller/common/rollout_controller.go, internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/isbservicerollout/isbservicerollout_controller_test.go, internal/controller/isbservicerollout/isbservicerollout_progressive.go, internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/monovertexrollout/monovertexrollout_progressive.go, internal/controller/pipelinerollout/pipelinerollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_progressive.go, internal/controller/progressive/progressive.go, internal/controller/progressive/progressive_test.go, pkg/apis/numaplane/v1alpha1/isbservicerollout_types.go, pkg/apis/numaplane/v1alpha1/monovertexrollout_types.go, pkg/apis/numaplane/v1alpha1/pipelinerollout_types.go, pkg/apis/numaplane/v1alpha1/progressive_status_types.go, tests/e2e/common.go, tests/e2e/functional-e2e/functional_test.go, tests/e2e/isbservice.go, tests/e2e/monovertex.go, tests/e2e/pipeline.go
Fixes #550 
This fixes a few issues (all of them are described inline):
- Reset the entire Upgrading Child Status and Promoted Child Status instead of just setting the inner structs that are common to all Rollouts
- Make sure to reset the Promoted Child Set if there's a new promoted child (it didn't look like we were)
- Make sure the Assessment of ISBService isn't dependent on the Pipeline still being there (it could be deleted)
- Premature success was being declared if it succeeded just once within the time window
- copy/paste error
- functional test bug for progressive case
Ran e2e test many times, all passing.
**Manual testing:**
For **MonoVertex**, I did a test in which I:
1. Create MonoVertexRollout with scale.min/max=3,6
2. Update image to a bad one
3. Observe initial MonoVertex …
=> fix: various bugs related to progressive rollout

tests/e2e/isbservice.go, tests/e2e/monovertex.go, tests/e2e/numaflowcontroller.go, tests/e2e/pipeline.go
Fixes #577 
This PR makes all functions used in the e2e test suite public to increase ease for writing new test suites and allowing use of all minor functions. 
This also makes debugging any new issues with test cases much simpler. In the future all new functions will be public as well to keep consistency.  
Running e2e test locally and on CI.
N/A
=> feat: make all e2e tests functions public

tests/e2e/common.go, tests/e2e/functional-e2e/functional_test.go, tests/e2e/isbservice.go, tests/e2e/numaflowcontroller.go, tests/e2e/ppnd-e2e/ppnd_test.go
Fixes #588 
Improves e2e testing by updating the `UpdateISBServiceRollout` and `UpdateNumaflowControllerRollout` functions to take an array of PipelineRollout names instead of a singular one. This allows us to check multiple Pipelines behavior as we proceed through an update of an ISBService or NumaflowController.
To ensure this, I have added a PipelineRollout `another-pipeline-rollout` to our functional test run which we check alongside the initial PipelineRollout which we update.
Running e2e tests locally and checking that CI run is successful.
N/A
=> feat: e2e test improvement - update functions can check multiple pipelines behavior

.github/workflows/ci.yaml, Makefile, tests/e2e/common.go, tests/e2e/functional-e2e/functional_test.go, tests/e2e/isbservice.go, tests/e2e/monovertex.go, tests/e2e/numaflowcontroller.go, tests/e2e/pipeline.go, tests/e2e/ppnd-e2e/ppnd_test.go
Fixes #500 
- Removing Documentation fn call and created a wrapper method for `Eventually()` and `Consistently()` for printing the test case name as well while run.
=> fix: (E2E) Remove Document fn call and refactor

internal/controller/monovertexrollout/monovertexrollout_progressive.go, internal/controller/pipelinerollout/pipelinerollout_progressive.go, tests/e2e/functional-e2e/functional_test.go, tests/e2e/numaflowcontroller.go, tests/e2e/pipeline.go, tests/e2e/ppnd-e2e/ppnd_test.go
Fixes #584 
Removed the check for which the scaleTo value should not be 0.
On the E2E tests, added a `scaleInVertex` arg on the `UpdatePipelineRollout` as a workaround to force scale up the `in` vertex back to 3 pods since after pausing a pipeline and resuming it, the scale values are ignored by Numaflow and we have to manually change the replicas on the vertex. This is similar to the scale down workaround adopted on the other E2E tests and that will be removed once the Numaflow changes/fixes are available. 
Manually tested by creating a MonoVertex and Pipeline with no scale values set.
None.
=> fix: scaling to zero behavior fix

config/crd/bases/numaplane.numaproj.io_isbservicerollouts.yaml, config/crd/bases/numaplane.numaproj.io_monovertexrollouts.yaml, config/crd/bases/numaplane.numaproj.io_pipelinerollouts.yaml, config/install.yaml, pkg/apis/numaplane/v1alpha1/isbservicerollout_types.go, pkg/apis/numaplane/v1alpha1/monovertexrollout_types.go, pkg/apis/numaplane/v1alpha1/pipelinerollout_types.go, pkg/apis/numaplane/v1alpha1/shared_types.go
The `strategy` field for PipelineRollout, ISBServiceRollout, and MonoVertexRollout was not configured as `omitempty`. This was causing it to be configured as a "required" field in the CRDs. Trying to apply our sample Rollouts was failing since the field wasn't in there. 
Also, I updated the child fields to be `omitempty` as well. 
```
jvogelman@macos-VF3V14X2QJ numaplane % k apply -f config/samples/numaplane.numaproj.io_v1alpha1_isbservicerollout.yaml                   
isbservicerollout.numaplane.numaproj.io/my-isbsvc created
jvogelman@macos-VF3V14X2QJ numaplane % k apply -f config/samples/numaplane.numaproj.io_v1alpha1_pipelinerollout.yaml  
pipelinerollout.numaplane.numaproj.io/my-pipeline created
jvogelman@macos-VF3V14X2QJ numaplane % k apply -f …
```
=> fix: enable certain fields related to "strategy" to be optional in the Rollouts

tests/e2e/common.go, tests/e2e/functional-e2e/functional_test.go, tests/e2e/monovertex.go, tests/e2e/pipeline.go
Increased the scale values for Pipeline and MonoVertex in the E2E tests to verify scaling logic.
E2E tests execution.
None.
=> chore: increase scale values for source vertex in E2E tests

tests/e2e/common.go, tests/e2e/functional-e2e/functional_test.go, tests/e2e/monovertex.go, tests/e2e/pipeline.go, tests/e2e/ppnd-e2e/ppnd_test.go
Fixed E2E tests by:
- removing time.sleep lines that are executed at the beginning of the test suite instead of after each `It` node
- adding more source vertex pods
- increasing `PauseGracePeriodSeconds` since pausing the pipeline was not draining it before the timeout would occur
E2E tests successful execution.
None.
=> fix: increased number of pods for the source vertex for all strategies and other e2e tests fixes

internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_controller.go
Mostly Fixes #602
Eventually, I'd like to have a local cache to store the Rollout Status, since we are the only ones writing to it. 
For now, however, I have updated the code to get the live Rollout every time to prevent cases like that identified by #602. 
I ended up doing this for the PipelineRollout, ISBServiceRollout, and MonoVertexRollout, since they are involved in the Progressive rollout case, in which we need to make sure we have the latest and greatest `Status` since we use that information that we previously wrote to inform what we do next.
Thus, I didn't end up changing NumaflowControllerRollout and NumaflowController because I don't believe we do anything like that for those. 
I mostly no longer see the resource version conflict errors for these Rollouts in the CI logs. (I …
=> fix: get just the live rollout resource when reconciling to avoid issues caused by getting cached status

tests/e2e/common.go, tests/e2e/functional-e2e/functional_test.go, tests/e2e/pipeline.go, tests/e2e/ppnd-e2e/ppnd_test.go
Updated Numaflow version to v1.4.3-rc for PPND E2E tests and made a common variable to be used for both PPND and functional tests.
=> chore: update Numaflow version to v1.4.3-rc in PPND E2E tests

tests/e2e/common.go
I saw a ppnd-e2e [test](https://github.com/numaproj/numaplane/actions/runs/13599582687/job/38023310598) that failed due to a pipeline never reconciled as "Running" after isbsvc was recreated. It had 4 minutes. I ran this change to make it 6 minutes through the CI a few times and it passed each time, so I'm hoping this takes care of it. 
The issue seemed to be that after the isbsvc gets updated to a new version, the pipeline stays in an unhealthy state for awhile saying "isbsvc is unhealthy" - for some reason, that process is a little slow. I'm not sure if it has anything to do with the fact that our source vertex now has 5 pods when it used to have 1 or not.
Ran through CI 3 times and it passed
N/A
=> fix: elongate test timeout time

internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_controller.go
Fixes #602
As part of PR #606, I made it so that we get the live version of the PipelineRollout, MonoVertexRollout, and ISBServiceRollout. This was to make it so we have the latest and greatest Status for these, since we need to use that Status to make decisions as part of "Progressive" logic. This makes it so that we don't have resource version conflict errors that are due to the fact that we retrieved a cached version of the Rollout which had an older resource version in it.
The one thing it did not address was the possibility that somebody may update the other parts of the Rollout (spec, etc) in between when we get the live rollout and go to update the Status. So, I am taking care of that a different way now. If there's a conflict error when writing the Status, I'm getting the live one …
=> feat: retry status update after failure for PipelineRollout, ISBServiceRollout, MonoVertexRollout

pkg/apis/numaplane/v1alpha1/isbservicerollout_types.go, pkg/apis/numaplane/v1alpha1/monovertexrollout_types.go, pkg/apis/numaplane/v1alpha1/pipelinerollout_types.go, pkg/apis/numaplane/v1alpha1/progressive_status_types.go
Fixes #615 
Removed arbitrary max date for the assessmentEndTime field.
Verified manually that the assessmentEndTime no longer shows in the status if unset and that progressive upgrade still works as expected.
None.
=> fix: remove assessmentEndTime max date

tests/e2e/common.go, tests/e2e/numaflowcontroller.go
I noticed we weren't watching the "kind" `NumaflowController` so I added it.
I now see it being printed as a file `numaflowcontroller.yaml` in the CI in the same directory as `numaflowcontroller_rollout.yaml`
N/A
=> chore: watch numaflowcontroller kind during e2e

internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/numaflowcontroller/numaflowcontroller_controller.go, internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_controller.go
Fixes https://github.com/numaproj/numaplane/issues/607
- Fixed deletion cycle for rollout
- Updated method `Update()` with `Patch()` for updating the resources
- Fix Get Live rollouts resouce
- Ran E2E Tests locally in kind cluster
=> fix: Update deleting cycle for rollouts

config/samples/numaplane.numaproj.io_v1alpha1_monovertexrollout.yaml, internal/controller/common/numaflowtypes/monovertex.go, internal/controller/common/numaflowtypes/pipeline.go, internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/isbservicerollout/isbservicerollout_progressive.go, internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/monovertexrollout/monovertexrollout_controller_test.go, internal/controller/monovertexrollout/monovertexrollout_progressive.go, internal/controller/pipelinerollout/pipelinerollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_progressive.go, internal/controller/progressive/progressive.go, internal/controller/progressive/progressive_test.go
This PR takes care of MonoVertex only - Pipeline can be done later. 
It does the following:
- Upon failure, scales the MonoVertex down to 0 Pods
- If "force promote" is done, scale it back up to the value specified in the MonoVertexRollout
(Note that for the latter, we may ultimately want to not get it from the MonoVertexRollout but instead save the `scaleDefinition` in the UpgradingChildStatus just like we do right now for Promoted child. Just thinking of very rare edge cases in which someone just changed the scale in the MonoVertexRollout and we use that instead of the one we were using. Normally, it would be fine to just use that scale value, but thinking of some rare case in which it's important that the scale value gets set atomically with some other change....) 
Ran various …
=> feat: Scale down failed MonoVertex to 0 Pods 

config/install.yaml, config/manager/controller-config.yaml, tests/manifests/special-cases/no-strategy/controller-config.yaml, tests/manifests/special-cases/progressive/controller-config.yaml
Fixes #TODO
It seems that having a trailing blank space after a line in the ConfigMap causes the formatting to get messed up if you do `kubectl get configmap <name> -o yaml`, like this:
```
apiVersion: v1
data:
config.yaml: "logLevel: DEBUG \nincludedResources: \"group=apps,kind=Deployment;group=,kind=ConfigMap;group=,kind=ServiceAccount;group=,kind=Secret;group=,kind=Service;group=rbac.authorization.k8s.io,kind=RoleBinding;group=rbac.authorization.k8s.io,kind=Role\"\ndefaultUpgradeStrategy:
\"progressive\"\nprogressive:\n  defaultAssessmentSchedule: \n    \n"
kind: ConfigMap
```
Removed the two blank spaces and now it looks like this:
```
apiVersion: v1
data:
config.yaml: |
logLevel: DEBUG
includedResources: "group=apps,kind=Deployment;\ …
```
=> fix: remove blank spaces from configmap

internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/numaflowcontroller/numaflowcontroller_controller.go, internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_controller.go
Fixes #632 
- Add logger and stop reconciler for resource not found error after resource got deleted.
- Ran E2E test locally in kind cluster
=> fix: Add safe check for not found error

tests/e2e/common.go
Quick fix to make not finding a pod while streaming logs no longer a fatal error. This pod can simply be skipped over and goroutine killed when this occurs.
Was the result of a flakey test which tried to stream a pod that was quickly deleted.
Running tests on CI.
N/A
=> fix: update streamPodLogs func to not fail when pod isn't found

config/crd/bases/numaplane.numaproj.io_monovertexrollouts.yaml, config/crd/bases/numaplane.numaproj.io_pipelinerollouts.yaml, config/install.yaml, internal/controller/isbservicerollout/isbservicerollout_progressive.go, internal/controller/monovertexrollout/monovertexrollout_progressive.go, internal/controller/pipelinerollout/pipelinerollout_progressive.go, internal/controller/progressive/progressive.go, internal/controller/progressive/progressive_test.go, pkg/apis/numaplane/v1alpha1/progressive_status_types.go
Fixes #639 
- Added a function to check if the ready replicas are at least equal to the desired replicas for a MonoVertex and Pipeline vertices. This function is used to perform the child health assessment during progressive upgrades.
- Implemented the upgrading child scaling (for MonoVertex only) to result in having a total number of running pods during upgrade that is equal to the number of running pods prior to the start of the progressive upgrade. This is performed by reducing the promoted MonoVertex running pods by half and applying the remaining pods (initially running pods - desired scale value on promoted MonoVertex) to the upgrading MonoVertex.
- Video MonoVertex Tests (no upgrading child scaling): https://drive.google.com/file/d/17rwrbrezUxSYu5Wp-rO1m4tjJVEpOd74/view?usp=drive_li …
=> feat: verify replicas for child health

internal/common/common.go, internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_controller.go
Derek requested that we not allow the index suffix on the child name to get too high, for the purpose of readability. Therefore, I am rolling over to 0 after 999. 
I decided not to take any extra precaution that the user isn't already running a child name of "-0" at that time. That would only happen in the very strange case that they did a Progressive update 999 times, each one failing, which would cause the "-0" one to still be there. 
Tested isbservicerollout, pipelinerollout, and monovertexrollout by temporarily setting the value as 3 and observing that after multiple progressive updates, after it hit "-3", the next one was "-0".
N/A
=> feat: keep child index from getting too high, for readability

internal/controller/isbservicerollout/isbservicerollout_progressive.go, internal/controller/monovertexrollout/monovertexrollout_progressive.go, internal/controller/pipelinerollout/pipelinerollout_progressive.go, internal/controller/progressive/progressive.go, internal/controller/progressive/progressive_test.go
Scale the upgrading MonoVertex deemed successful for promotion to the Rollout scale values immediately after the assessment has been completed.
https://drive.google.com/file/d/187BIbKxIyzDhk5Jw59Uf6quMuVErXzJy/view?usp=drive_link
None
=> fix: scale upgrading MonoVertex to desired scale values once deemed successful for promotion

internal/controller/pipelinerollout/pipelinerollout_controller.go, tests/e2e/common.go
Fixes an internal issue.
We were seeing a case where a quick pause for updating the image of a PipelineRollout could cause a resource conflict error when updating the child and result in the pauseStatus of the rollout not being updated properly. This would cause the reported pause metrics to use the previously set status resulting in a much longer pause time than we should expect.
This is fixed by moving where we set the metric to avoid any erroneous values.
Testing locally with a long pause and seeing that the metric updates properly.
N/A
=> fix: update when pausing metrics are set to avoid edge case for quick pause showing as a longer pause

Makefile, tests/manifests/default/kustomization.yaml, tests/manifests/default/rollouts-ns.yaml
Since Numaplane will now require Argo Rollouts, we can run Argo Rollouts whenever we run Numaplane.
This runs argo-rollouts in the "argo-rollouts" namespace, and in a "cluster mode", such that it reconcile from any namespace.
standard CI
N/A
=> chore: Run Argo Rollouts when we run Numaplane

config/crd/bases/numaplane.numaproj.io_monovertexrollouts.yaml, config/crd/bases/numaplane.numaproj.io_pipelinerollouts.yaml, config/install.yaml, pkg/apis/numaplane/v1alpha1/shared_types.go
Inline tag was set on the Progressive field instead of the PipelineTypeProgressiveStrategy on the PipelineTypeRolloutStrategy struct. This was causing the [E2E tests I'm working on](https://github.com/numaproj/numaplane/pull/660) to fail adding the strategy to the MonoVertex spec.
E2E tests create the MonoVertex with the expected strategy.
None.
=> fix: fix for inline tag on progressive field

tests/e2e/functional-monovertex-e2e/monovertex_test.go, tests/e2e/functional-nc-e2e/numaflow-controller_test.go
Replaced UDSink with Balckhole sink to avoid `too many open files` error.
E2E tests not showing that error.
None.
=> chore: sink to blackhole to avoid 'too many open files' error

config/crd/bases/numaplane.numaproj.io_isbservicerollouts.yaml, config/crd/bases/numaplane.numaproj.io_monovertexrollouts.yaml, config/crd/bases/numaplane.numaproj.io_pipelinerollouts.yaml, config/install.yaml, internal/controller/isbservicerollout/isbservicerollout_progressive.go, internal/controller/monovertexrollout/monovertexrollout_progressive.go, internal/controller/pipelinerollout/pipelinerollout_progressive.go, internal/controller/progressive/progressive.go, internal/controller/progressive/progressive_test.go, pkg/apis/numaplane/v1alpha1/monovertexrollout_types.go, pkg/apis/numaplane/v1alpha1/pipelinerollout_types.go, pkg/apis/numaplane/v1alpha1/progressive_status_types.go
Part of: https://github.com/numaproj/numaplane/issues/670
- Add progressive rollout failure reason in case of failure
Verified in local kubernetes cluster
```bash
Progressive Status:
Promoted Mono Vertex Status:
Name:                               test-monovertex-rollout-0
Scale Values Restored To Original:  true
Upgrading Mono Vertex Status:
Analysis:
Phase:
Assessment End Time:     2025-03-26T14:57:58Z
Assessment Result:       Failure
Assessment Start Time:   2025-03-26T14:56:58Z
Failure Reason:          readyReplicas=1 is less than desiredReplicas=3
Name:                    test-monovertex-rollout-1
Original Scale Min Max:  {"max":null,"min":5}
Upgrade In Progress:         Progressive
```
=> feat: Add failure reason for progressive rollout

internal/controller/progressive/progressive.go
Fixes https://github.com/numaproj/numaplane/issues/680
- Fixed the mismatch between FailureReason and child status
- Verified in local k8s cluster after deploying the changes, ran `STRATEGY=progressive make test-progressive-e2e` and keep deleting the newly created pod during upgrade to cause failure.
=> fix: mismatch between FailureReason and child status

internal/controller/monovertexrollout/monovertexrollout_progressive.go, internal/controller/pipelinerollout/pipelinerollout_progressive.go, internal/controller/progressive/analysis.go
Fixes #691 
Fixes issue where we were not adding an OwnerReference to related AnalysisRuns that are created during a Progressive upgrade that uses them.
Running progressive upgrades locally on MonoVertexRollout and checking the created AnalysisRun is created with a ownerReference and is deleted when the rollout is.
```
- apiVersion: argoproj.io/v1alpha1
kind: AnalysisRun
metadata:
creationTimestamp: "2025-04-07T23:59:28Z"
generation: 2
labels:
app.kubernetes.io/part-of: numaplane
name: my-monovertex-1
namespace: example-namespace
ownerReferences:
- apiVersion: numaflow.numaproj.io/v1alpha1
blockOwnerDeletion: true
controller: true
kind: MonoVertex
name: my-monovertex-1
uid: 1cf0d96d-0cda-4fd7-890c-30ff3caf2f55
resourceVersion: "890142"
uid: 8ed46273-5310-4cee-922e-415e10909d8f
```
n/a
=> fix: add OwnerReferences to created AnalysisRuns

internal/common/common.go, internal/controller/progressive/progressive.go
Currently we have a force-promote field on the parent rollout which can be set to force promote a child even if the progressive upgrade is failed. This may cause issues for later progressive upgrades however if the user does not remember to remove or set this field to false for their next upgrades.
To remedy this, we can check for a `force-promote` label on the upgrading child during the assessment and force a success that way. Thus when the current upgrade happens, this child becomes the currently promoted and the label will be ignored. 
Testing locally with failed progressive upgrade that passes after setting the label on the upgrading child.
n/a
=> feat:  adding label to upgrading child will force promotion during progressive upgrade

internal/controller/isbservicerollout/isbservicerollout_controller.go
Partly Fixes #704 
- Removed the foreground deletion
- Delete the ISBService child object first before removing finalizer whenever deletion request is received for ISBServiceRollout.
=> fix: Removed foreground deletion and updated deletion process for ISBSVC

internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/numaflowcontroller/numaflowcontroller_controller.go, internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_controller.go
Fixes #TODO
- Temporarily comment the foreground deletion code, unless we have a proper fix by this issue https://github.com/numaproj/numaplane/issues/704
- Verified in local k8s cluster, now parent resource is not waiting for child to get deleted.
=> fix: Temporarily comment the foreground deletion

internal/controller/common/rollout_controller.go, internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_controller.go
Fixes #706 
Adds support for templated definitions of child resources in MonoVertexRollout, PipelineRollout and ISBServiceRollout. This is needed to allow for our rider resources to be referenced by child resources and vice versa.
Adding an annotation and a volume to each a MonoVertexRollout, PipelineRollout and ISBServiceRollout which use the arguments we currently support for name and namespace. Below is the MonoVertexRollout spec and the resulting MonoVertex child after a progressive upgrade. 
Rollout spec: 
```
apiVersion: numaplane.numaproj.io/v1alpha1
kind: MonoVertexRollout
metadata:
name: my-monovertex
namespace: example-namespace
spec:
strategy:
progressive:
assessmentSchedule: "60,60,10"
analysis:
args:
templates:
monoVertex:
#uncomment for Progressive rollout to set Numaflow …
```
=> feat: add templating for monovertex/pipeline/isbservice spec and metadata

internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_controller.go
Part of: #704 
- Removed foreground deletion code
- Added logic to delete dependent pipeline before removing the finalizer from pipelineRollout
=> fix: Removed foreground deletion from pipeline rollout

internal/controller/progressive/progressive.go
This fixes a bug in which after failure case, the previous "upgrading child" was being used to perform `ProcessUpgradingChildPostUpgrade()` rather than the new one.
Thankfully, only ISBServiceRollout implements anything that happens in `ProcessUpgradingChildPostUpgrade()` at least, but it was operating on the wrong child.
Updated ISBServiceRollout to cause failure. Then updated a second time. Observed that the PDB created was for the new isbsvc.
n/a
=> fix: post-failure code was referring to the old upgrading child rather than the new one

go.mod, internal/controller/common/rollout_controller.go, internal/controller/common/rollout_controller_test.go, internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_controller.go
Instead of having the kludgey approach of replacing the hyphenated arguments in a rollout spec before evaluating it as a template, we can utilize the `fasttemplate` package which can evaluate these arguments without error. 
Testing multiple Pipeline and MonoVertex rollouts after progressive upgrades to see the values in the child resources are updated properly.
n/a
=> feat: improve templating by evaluating rollout specs with hyphenated arguments

internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/numaflowcontroller/numaflowcontroller_controller.go, internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller.go
Part of: https://github.com/numaproj/numaplane/issues/704
- Removed finalizer from MonoVertex
- Removed finalizer from NumaflowController
- Modified and moved dependent resource check from NC to NCR
- Auto Heal Numaflow Controller if it is deleted and child resource is still available in cluster
Verified in local k8s cluster
=> fix: fix foreground deletion for NC and monovertex

config/samples/numaplane.numaproj.io_v1alpha1_isbservicerollout.yaml, config/samples/numaplane.numaproj.io_v1alpha1_pipelinerollout.yaml, internal/controller/common/rollout_controller.go, internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_controller.go, internal/controller/progressive/progressive.go, internal/controller/progressive/progressive_test.go
Incorporate the same Rider functionality into Pipeline and isbsvc.
Main difference: Pipeline also implements "per-vertex" capability. In order to do this, I realized I needed to adjust the signature for `GetDesiredRiders()` to add another argument. 
Tried different scenarios for riders for pipeline and isbsvc, both with progressive and ppnd strategy. For pipeline, specifically tried a per-vertex VPA resource. 
Also did some retesting of MonoVertex since I changed a little bit there.
N/A
=> feat: Riders for pipeline and isbsvc

internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/numaflowcontroller/numaflowcontroller_controller.go
Fixes https://github.com/numaproj/numaplane/issues/704
This change will fix the issue regarding finalizer left on resource after deletion.
- Removing existing finalizer for monovertex and controller
- Verified on local k8s
=> fix: Removing existing finalizer for monovertex and controller

internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_controller.go
I noticed some log lines which were accidentally written using `Info()` rather than `Infof()`.
N/A
N/A
=> fix: log line formatting

config/install.yaml, config/rbac/numaplane-aggregate-to-admin.yaml, config/rbac/numaplane-aggregate-to-edit.yaml, config/rbac/numaplane-aggregate-to-view.yaml
There are some ClusterRoles which are associated with user accounts at Intuit. 
For example, the `numaplane-aggregate-to-admin` ClusterRole is connected to the user accounts which are "DevOps" within the [oss-analytics DevPortal organization](https://devportal.intuit.com/app/dp/project/5407714845444489299/members). 
The ClusterRoles never got updated to include `NumaflowController` CRD
=> fix: add ClusterRoles to enable users to read/write NumaflowController resource

internal/common/common.go, internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/isbservicerollout/isbservicerollout_controller_test.go, internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/monovertexrollout/monovertexrollout_controller_test.go, internal/controller/pipelinerollout/pipelinerollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_controller_test.go, internal/controller/progressive/progressive.go
Fixes #739 
If a user deletes a Promoted child while in the middle of Progressive upgrade (could be prior to Assessment or after it's failed), then in addition to the Promoted child being recreated, any Upgrading children are deleted and then `upgradeInProgress` field is set back to "".
For each of the 3 rollouts, tested prior to Assessment and after Assessment failure. Then I also, just in case, did a subsequent Progressive upgrade just to make sure that worked fine too. 
N/A
=> fix: Handle deletions of promoted child gracefully

internal/controller/config/config.go, internal/controller/progressive/progressive.go
Fixes #740 
Added the progressive upgrade `rolloutObject`, `promotedChild`, and `upgradingChild` fields to the logs to help with debugging via Splunk.
Created the `progressive.logObjects` config var to only enable these detailed logs only on clusters.
Manually verified the logs locally.
None.
=> feat: add some important progressive upgrade related fields to the logs

.github/workflows/ci.yaml, Makefile, tests/e2e/progressive-monovertex-e2e/monovertex_test.go, tests/e2e/progressive-pipeline-e2e/pipeline_test.go
Separated MonoVertex from Pipeline E2E tests.
E2E tests passed.
None.
=> chore: separated monovertex and pipeline progressive e2e tests

internal/controller/monovertexrollout/monovertexrollout_progressive.go, internal/controller/pipelinerollout/pipelinerollout_progressive.go
Fixes #TODO
Code was setting the upgrading child to 1 pods if the `Initial` was 0. This code was added for the purpose of handling the case of a "promoted" child which was supposed to have more than 0 Pods but some failure was causing only 0 Pods to exist.
We need to also account for the case in which the user really does intend for min=max=0.
Tested both PipelineRollout and MonoVertexRollout using min and max set to 0 in the spec.
For PipelineRollout, I tried a 3 vertex Pipeline with scale set to min=max=0 for one Vertex, `scale` not set for another, and `scale` set but `min` and `max` not set for another. Observed that only the Vertex with min=max=0 was actually scaled to 0 in the new Pipeline.
=> fix: correctly handle scale.max=0 case for MonoVertex and Pipeline

tests/e2e/progressive-monovertex-e2e/monovertex_test.go, tests/e2e/progressive-pipeline-e2e/pipeline_test.go, tests/e2e/progressive.go
Fixes #756 
When updating Pipeline and associated ISBService at the same time, check that the ISBService Progressive Status is failed if the upgrading Pipeline has failed (even if the ISBService change is good).
E2E tests pass.
None.
=> chore: progressive E2E tests to check ISBService status when Pipeline upgrade fails

internal/common/common.go, internal/controller/common/rollout_controller_test.go, internal/controller/monovertexrollout/monovertexrollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_controller_test.go, internal/controller/progressive/progressive.go, tests/manifests/default/controller_def_1.5.0-rc2.yaml, tests/manifests/default/controller_def_1.5.0-rc3.yaml
Fixes #535 
No longer wait until Assessment is complete and failed to replace the upgrading child with a new one. 
Now while we're in Progressive, we can just check if there's a difference between the current "upgrading" one and the current Rollout spec to determine if we want to preempt the current upgrade with a new one. 
When deleting previous Pipeline, we have been pausing and requiring the Pipeline to be fully drained in order for it to be deleted. This means that if it doesn't drain successfully, the old Pipeline will remain for user to need to delete on their own. Until we make this configurable, I think we should default to not requiring drain for the deletion (this is described inline).
Created PipelineRollout and ISBServiceRollout. Updated both at the same time to a new spec …
=> feat: Preempt progressive upgrade in progress if there's a new spec

internal/controller/monovertexrollout/monovertexrollout_controller_test.go
Fixes #703 
Adds a unit test to fully test out AnalysisRun implementation by checking that AnalysisRun is generated during a progressive upgrade. This differs from our progressive upgrade unit testing as we do not reconcile the AnalysisRun (we are using an already reconciled AnalysisRun in the other tests).
Running locally and on CI.
n/a
=> feat: add unit test to test AnalysisRun generation during a progressive upgrade

.github/workflows/ci.yaml, internal/controller/progressive/progressive.go
CI was timing out for Unit Tests and Codegen.
Ran CI multiple times
N/A
=> chore: increase timeouts on codegen and unit tests in CI

internal/controller/numaflowcontroller/numaflowcontroller_controller.go
Fixes https://github.com/numaproj/numaplane/issues/783 
Fixes https://github.com/numaproj/numaplane/issues/787
- Handle case for pruning resource when it's deleted in new version
- List all the resources in cluster whose owner reference API Version is `numaplane`
- Then compute the diff with upcoming resource and remove if any.
Verified in local k8s cluster with below scenatios
Case: 1
- Deployed `NumaflowController` v1.4.2 which has the `numaflow-server`, then deployed `NumaflowController` v1.4.3 which doesn't have `numaflow-server`. As expected `numaflow-server` is removed.
Case: 2
- Cluster is running `numaflow-server` which is not in current manifest due to bug in `Numaplane-controller`, Then updated the `numaplane-controller` with the fix image, as expected `numaflow-server` is …
=> fix: Prune NumaflowController resource which are removed in latest version

internal/controller/isbservicerollout/isbservicerollout_controller.go, internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller.go, internal/controller/pipelinerollout/pipelinerollout_controller.go, internal/usde/usde.go
When I was looking at splunk logs, there were some logs that were too noisy and others that I wished I saw but didn't exist.
Specifically, the usde was logging every [field](https://github.com/numaproj/numaplane/blob/main/config/manager/usde-config.yaml#L9-L118) described in the usde-config.yaml file that it checked. I removed that and replaced with a single line to indicate if a particular field is deemed to require an update. 
I also added some logging to indicate when the finalizers of the various numaplane resources are removed.
Did a local progressive test to verify the USDE log change. Deleted a rollout and verified the line for removing the finalizer showed.
N/A
=> chore: reduce some very noisy logging; add some other logging

tests/e2e/analysistemplate.go, tests/e2e/common.go, tests/e2e/isbservice.go, tests/e2e/monovertex.go, tests/e2e/numaflowcontroller.go, tests/e2e/pipeline.go, tests/e2e/progressive.go
I noticed a couple of places where I was calling `CheckConsistently()`, and unfortunately if you forget to override the default test timeout, it sets it to 6 minutes. I want to make the default much shorter.
This reduces the pipeline-progressive test from 32 minutes to 21 :) 
e2e still passes, observed the Consistently check took only 15 seconds
n/a
=> fix: default timeout for Consistently() check should be much shorter 

Makefile, tests/e2e/common.go, tests/e2e/progressive-analysis-monovertex-e2e/analysis_monovertex_test.go, tests/manifests/default/prometheus-monitors.yaml
1. Updated prometheus query to match the one we're applying to clusters
2. Added "AnalysisRun" to the list of artifacts that are saved when running e2e
n/a
n/a
=> chore: update prometheus query in AT test to reflect what we're using

config/samples/numaplane.numaproj.io_v1alpha1_monovertexrollout.yaml, config/samples/numaplane.numaproj.io_v1alpha1_pipelinerollout.yaml, internal/controller/config/config.go, internal/controller/progressive/analysis.go
This adds a feature flag for ignoring the result of the AnalysisRun as part of the assessment of either Pipeline or MonoVertex.
I've also updated our sample MonoVertexRollout to use the AnalysisTemplate we're using on clusters.
Did two tests: once with the feature flag turned on and once with it turned off. Verified that the result was ignored in the former case and not in the latter.
N/A
=> chore: Feature flag to ignore AnalysisRun result

config/samples/numaplane.numaproj.io_v1alpha1_monovertexrollout.yaml, internal/controller/progressive/progressive.go
I noticed this log line wasn't showing the correct name of the upgrading child. The issue is the location of the log line. 
Verified log line while executing.
N/A
=> fix: logging needs to reference the right name of the resource

tests/e2e/isbservice.go, tests/e2e/pipeline.go, tests/e2e/progressive-analysis-monovertex-e2e/analysis_monovertex_test.go, tests/e2e/progressive-analysis-pipeline-e2e/analysis_pipeline_test.go, tests/e2e/progressive-pipeline-e2e/pipeline_test.go
Fixes https://github.com/numaproj/numaplane/issues/750
- Use two analysis template for MonoVertex analysis tests for success and failure case.
- Add failure test case for pipeline analysis e2e 
=> fix: Add two analysis template for monovertex and failure tests for pipeline

cmd/main.go, internal/controller/ginkgo_suite_test.go, internal/controller/isbservicerollout/isbservicerollout_controller_test.go, internal/controller/monovertexrollout/monovertexrollout_controller_test.go, internal/controller/numaflowcontrollerrollout/numaflowcontrollerrollout_controller_test.go, internal/controller/pipelinerollout/pipelinerollout_controller_test.go, internal/sync/cache_test.go, internal/util/metrics/metrics.go
Fixes #TODO
- Added the info log while deleting the metrics durning deletion of  pipelineRO, monovertexRO, .....
=> fix: Add info logger while removing metrics

config/install.yaml, config/manager/controller-config.yaml, config/rbac/role.yaml, tests/manifests/default/config.yaml, tests/manifests/e2e/special-cases/no-strategy/controller-config.yaml, tests/manifests/e2e/special-cases/pause-and-drain/controller-config.yaml
Adds `HorizontalPodAutoscaler` as allowed Kind for Rider. Updates `numaplane-role` to include HPA to be able to create them.
Tested locally with MonoVertexRollout spec below.
```
apiVersion: numaplane.numaproj.io/v1alpha1
kind: MonoVertexRollout
metadata:
name: my-monovertex
namespace: example-namespace
spec:
strategy:
progressive:
assessmentSchedule: "120,60,10"
analysis:
args:
templates:
- templateName: mvtx-acknowledged-messages
clusterScope: false
riders:
- definition:    
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
name: my-mvtx-hpa
spec:
minReplicas: 1
maxReplicas: 3
metrics:
- type: Resource
resource:
name: cpu
target:
type: Utilization
averageUtilization: 50
scaleTargetRef:
apiVersion: numaflow.numaproj.io/v1alpha1
kind: MonoVertex
name: …
```
=> feat: update RBAC/configMap to allow HPA as Rider kind

tests/e2e/progressive-analysis-monovertex-e2e/analysis_monovertex_test.go, tests/e2e/progressive-analysis-pipeline-e2e/analysis_pipeline_test.go
Fixes https://github.com/numaproj/numaplane/issues/826
- Rename analysis template name for pipeline and monovertex, which will help to debug failure test cases easily 
- Verified in local K8s cluster
=> fix: Rename analysis template name for pipeline and monovertex

internal/controller/monovertexrollout/monovertexrollout_controller.go
Part of: https://github.com/numaproj/numaplane/issues/798
- Add error log for AnalysisRuns controller watch
=> fix: log error for AnalysisRuns controller watch

internal/controller/common/rollout_controller.go, internal/controller/common/rollout_controller_test.go, internal/controller/pipelinerollout/pipelinerollout_controller_test.go
Fixes #871 
I realized that the function `FindMostCurrentChildOfUpgradeState()` looks for the most current child based on its index, but we have a [rollover capability](https://github.com/numaproj/numaplane/blob/main/internal/controller/pipelinerollout/pipelinerollout_controller.go#L1155-L1157) for index numbers, so the function won't work if there is a rollover.  
This one is hard to reproduce when running since it relies on there being 2 "promoted" children or 2 "upgrading" children, which is a rare state. 
But the unit test does check for it.  
N/A
=> fix: Finding the most current child shouldn't rely on the index

internal/controller/pipelinerollout/pipelinerollout_recycle.go, internal/util/metrics/metrics.go
Fixes #880 
Adding a new Counter metric `PipelineDrains` to keep track of pipelines which did and did not successfully drain fully (i.e. `drainedOnPause==true`).
My main goals were:
1. Be able to alert on a pipeline drain failure (i.e. if the total count of `PipelineDrains{"drainComplete"="false"}` increases).
2. Be able to know immediately which pipeline it was that failed.
I ran the CI test and saw this when port forwarding the numaplane port 8080:
```
progressive_pipeline_drains{drainComplete="true",incompleteReason="ForceDrain",intuit_alert="true",namespace="numaplane-system",pipeline="test-pipeline-rollout-1",pipelineRollout="test-pipeline-rollout"} 1
progressive_pipeline_drains{drainComplete="true",incompleteReason="ForceDrain",intuit_alert="true",namespace="numaplane-system",pipelin …
```
=> feat: Add metrics to track drain successes and incomplete drains
